const API_BASE="https://derofsthjivlkcdnojww.supabase.co/functions/v1/azaad-clinic";
const $=id=>document.getElementById(id);let selectedTime="";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function api(path,opt={}){const r=await fetch(API_BASE+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"تعذر الاتصال بالخادم");return d}
function msg(t,ok=false){$("message").textContent=t;$("message").style.color=ok?"#16734a":"#a13a3a"}
function renderServices(a=[]){let icons=["🧠","🌿","💙","🔎","✨","🫶"];$("servicesGrid").innerHTML=a.map((x,i)=>`<article class="card"><div class="icon">${icons[i%icons.length]}</div><h3>${esc(x.name)}</h3><p>${esc(x.description||"رعاية متخصصة وفق احتياجاتك.")}</p><p><b>${esc(x.duration_minutes||"")}</b> دقيقة</p></article>`).join("")||'<article class="card"><h3>الخدمات</h3><p>سيتم تحديث الخدمات قريبًا.</p></article>'}
function renderDoctors(a=[]){$("doctorsGrid").innerHTML=a.map(x=>`<article class="card"><div class="photo">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.name)}">`:esc((x.name||"A").charAt(0))}</div><h3>${esc(x.name)}</h3><p><b>${esc(x.title||"متخصص")}</b></p><p>${esc(x.bio||"")}</p></article>`).join("")||'<article class="card"><h3>فريق العيادة</h3><p>سيتم تحديث بيانات الأطباء قريبًا.</p></article>'}
function contacts(s={}){let p=s.phone||"",e=s.email||"",w=s.whatsapp||"";$("phoneText").textContent=p||"—";$("phoneLink").href=p?"tel:"+p:"#";$("emailText").textContent=e||"—";$("emailLink").href=e?"mailto:"+e:"#";let u=w?"https://wa.me/"+w.replace(/\D/g,""):"#";$("whatsappLink").href=u;$("heroWhatsapp").href=u;$("address").textContent=s.address||""}
async function init(){try{let d=await api("?api=data");renderServices(d.services);renderDoctors(d.doctors);contacts(d.settings||{});let n=new Date();n.setMinutes(n.getMinutes()-n.getTimezoneOffset());$("date").min=n.toISOString().slice(0,10);$("date").value=n.toISOString().slice(0,10);$("doctor").innerHTML='<option value="">اختر الطبيب</option>'+d.doctors.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.title||"")}</option>`).join("");$("service").innerHTML='<option value="">اختر الخدمة</option>'+d.services.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("")}catch(e){console.warn(e)}}
async function slots(){selectedTime="";if(!$("doctor").value||!$("service").value)return;$("slots").textContent="جاري تحميل المواعيد...";try{let d=await api(`?api=slots&doctor=${encodeURIComponent($("doctor").value)}&service=${encodeURIComponent($("service").value)}&date=${encodeURIComponent($("date").value)}`);$("slots").innerHTML=(d.slots||[]).map(t=>`<button type="button" class="slot" data-t="${esc(t)}">${esc(t)}</button>`).join("")||"لا توجد مواعيد متاحة";document.querySelectorAll(".slot").forEach(b=>b.onclick=()=>{document.querySelectorAll(".slot").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedTime=b.dataset.t})}catch(e){$("slots").textContent="تعذر تحميل المواعيد."}}
$("bookingForm").onsubmit=async e=>{e.preventDefault();if(!selectedTime)return msg("من فضلك اختر وقت الموعد.");try{let d=await api("?api=book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({doctor_id:$("doctor").value,service_id:$("service").value,appointment_date:$("date").value,appointment_time:selectedTime,mode:$("mode").value,patient_name:$("name").value,patient_phone:$("phone").value,patient_email:$("email").value,notes:$("notes").value})});msg("تم إرسال الحجز بنجاح. رقم الحجز: "+(d.booking_code||"—"),true);$("bookingForm").reset();selectedTime="";$("slots").textContent="تم استلام الطلب."}catch(e){msg(e.message)}};
["doctor","service","date"].forEach(id=>$(id).onchange=slots);$("year").textContent=new Date().getFullYear();init();