const API='https://derofsthjivlkcdnojww.supabase.co/functions/v1/azaad-clinic';const $=x=>document.getElementById(x);let chosen='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(q,opt){const r=await fetch(API+q,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'تعذر الاتصال');return d}
function render(d){$('servicesGrid').innerHTML=(d.services||[]).map((x,i)=>`<article class="card"><div class="icon">${['🧠','🌿','💙','🔎','✨'][i%5]}</div><h3>${esc(x.name)}</h3><p>${esc(x.description||'رعاية متخصصة وفق احتياجاتك.')}</p><p>${x.duration_minutes||30} دقيقة</p></article>`).join('');
$('doctorsGrid').innerHTML=(d.doctors||[]).map(x=>`<article class="card"><div class="photo">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.name)}">`:esc((x.name||'A')[0])}</div><h3>${esc(x.name)}</h3><p><b>${esc(x.title||'متخصص')}</b></p><p>${esc(x.bio||'')}</p></article>`).join('');
$('doctor').innerHTML='<option value="">اختر الطبيب</option>'+(d.doctors||[]).map(x=>`<option value="${x.id}">${esc(x.name)} — ${esc(x.title||'')}</option>`).join('');
$('service').innerHTML='<option value="">اختر الخدمة</option>'+(d.services||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');
const s=d.settings||{};$('phone').textContent=s.phone||'';$('phoneLink').href=s.phone?'tel:'+s.phone:'#';$('email').textContent=s.email||'';$('emailLink').href=s.email?'mailto:'+s.email:'#';const w=s.whatsapp?`https://wa.me/${String(s.whatsapp).replace(/\D/g,'')}`:'#';$('waLink').href=w;$('waHero').href=w;$('address').textContent=s.address||''}
async function init(){try{const d=await api('?api=data');render(d);const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());$('date').min=now.toISOString().slice(0,10);$('date').value=now.toISOString().slice(0,10)}catch(e){$('message').textContent='تعذر تحميل بيانات العيادة. يرجى المحاولة لاحقًا.'}}
async function loadSlots(){chosen='';if(!$('doctor').value||!$('service').value||!$('date').value){$('slots').textContent='اختر الطبيب والخدمة والتاريخ.';return}$('slots').textContent='جاري تحميل المواعيد...';try{const d=await api(`?api=slots&doctor=${encodeURIComponent($('doctor').value)}&service=${encodeURIComponent($('service').value)}&date=${encodeURIComponent($('date').value)}`);$('slots').innerHTML=(d.slots||[]).map(t=>`<button class="slot" type="button" data-t="${t}">${t}</button>`).join('')||'لا توجد مواعيد متاحة لهذا اليوم.';document.querySelectorAll('.slot').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');chosen=b.dataset.t})}catch(e){$('slots').textContent='تعذر تحميل المواعيد.'}}
$('bookingForm').onsubmit=async e=>{e.preventDefault();if(!chosen){$('message').textContent='من فضلك اختر موعدًا.';return}try{const d=await api('?api=book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({doctor_id:$('doctor').value,service_id:$('service').value,appointment_date:$('date').value,appointment_time:chosen,mode:$('mode').value,patient_name:$('name').value,patient_phone:$('phone').value,patient_email:$('email').value,notes:$('notes').value})});$('message').textContent='تم إرسال الحجز بنجاح. رقم الحجز: '+d.booking_code;$('message').style.color='#16734a';$('bookingForm').reset();chosen='';$('slots').textContent='تم استلام طلب الحجز.'}catch(e){$('message').textContent=e.message;$('message').style.color='#a13a3a'}};
['doctor','service','date'].forEach(id=>$(id).onchange=loadSlots);$('year').textContent=new Date().getFullYear();$('menu').onclick=()=>{const n=document.querySelector('nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='74px';n.style.right='0';n.style.left='0';n.style.background='#fff';n.style.padding='20px';n.style.flexDirection='column'};init();