(() => {
  'use strict';
  const CLINIC_API='https://derofsthjivlkcdnojww.supabase.co/functions/v1/azaad-public-clinic-data';
  const STATE='__AZAAD_CLINIC_POSTS_V9__';
  if(window[STATE]) return;
  const state={posts:[],started:false}; window[STATE]=state;
  const central=()=>window.AZAAD_I18N;
  const lang=()=>{const v=central()?.language?.();return v==='en'||v==='ar'?v:(document.documentElement.lang?.toLowerCase().startsWith('en')?'en':'ar');};
  const t=k=>central()?.t?.(k)??k;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const safeUrl=v=>{try{const u=new URL(String(v||'').trim());return ['http:','https:'].includes(u.protocol)?u.href:'';}catch(_){return '';}};
  async function request(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||d?.message||`HTTP ${r.status}`);return d;}finally{clearTimeout(timer);}}
  function postsSection(){let s=document.getElementById('clinicPosts');if(s)return s;s=document.createElement('section');s.id='clinicPosts';s.className='section section-light';s.innerHTML=`<div class="container"><div class="eyebrow" data-posts-i18n="postsEyebrow"></div><h2 data-posts-i18n="postsTitle"></h2><p class="section-intro" data-posts-i18n="postsIntro"></p><div id="clinicPostsGrid" class="cards"></div></div>`;const main=document.querySelector('main'),booking=document.getElementById('booking');if(booking?.parentNode)booking.parentNode.insertBefore(s,booking);else if(main)main.appendChild(s);return s;}
  function renderPosts(){const s=postsSection(),grid=document.getElementById('clinicPostsGrid');if(!s||!grid)return;s.querySelector('[data-posts-i18n="postsEyebrow"]').textContent='AZAAD CLINIC';s.querySelector('[data-posts-i18n="postsTitle"]').textContent=lang()==='en'?'Latest News & Articles':'آخر الأخبار والمقالات';s.querySelector('[data-posts-i18n="postsIntro"]').textContent=lang()==='en'?'Stay up to date with the latest medical news and articles. From new medical treatments to health tips and insights from medical specialists, our blog provides valuable information to help you make informed decisions about your health.':'إبقَ على إطلاعِ بآخر الأخبار الطبية والمقالات. من العلاجات الطبية الجديدة إلى نصائح الصحة وآراء الأخصائيين الطبيين، توفر مدونتنا معلومات قيمة يمكنها مساعدتك في إتخاذ قرارات مدروسة حول صحتك.';if(!state.posts.length){s.style.display='none';return;}s.style.display='';grid.innerHTML=state.posts.map(p=>{const title=lang()==='en'?(p?.title_en||p?.title||t('defaultPostTitle')):(p?.title||t('defaultPostTitle'));const content=lang()==='en'?(p?.content_en||p?.content||''):(p?.content||'');const date=p?.published_at?new Date(p.published_at).toLocaleDateString(lang()==='en'?'en-US':'ar-EG',{year:'numeric',month:'long',day:'numeric',timeZone:'Africa/Cairo'}):'';let media='';const u=safeUrl(p?.media_url);if(u&&p.media_type==='image')media=`<div class="clinic-post-media" style="width:100%;overflow:hidden;border-radius:14px;margin-bottom:16px"><img src="${esc(u)}" alt="${esc(title)}" loading="lazy" decoding="async" style="display:block;width:100%;height:auto;max-height:none;object-fit:contain;object-position:center;border-radius:14px"></div>`;if(u&&p.media_type==='video')media=`<div class="clinic-post-media" style="width:100%;overflow:hidden;border-radius:14px;margin-bottom:16px"><video controls preload="metadata" playsinline style="display:block;width:100%;height:auto;max-height:420px;border-radius:14px;background:#000"><source src="${esc(u)}">${esc(t('videoUnsupported'))}</video></div>`;const more=safeUrl(p?.external_url);return `<article class="card clinic-post-card" style="overflow:hidden">${media}<div>${date?`<div class="small-note" style="margin-bottom:8px">${esc(date)}</div>`:''}<h3>${esc(title)}</h3>${content?`<p>${esc(content)}</p>`:''}${more?`<a href="${esc(more)}" target="_blank" rel="noopener noreferrer" class="btn">${esc(t('postMore'))}</a>`:''}</div></article>`;}).join('');}
  async function load(){try{const d=await request(`${CLINIC_API}?_=${Date.now()}`);state.posts=(Array.isArray(d?.posts)?d.posts:[]).filter(p=>p&&p.published===true).sort((a,b)=>new Date(b.published_at||b.created_at||0)-new Date(a.published_at||a.created_at||0));renderPosts();}catch(e){console.warn('Azaad public posts:',e);}}
  function refresh(){renderPosts();}
  window.AZAAD_PUBLIC_RERENDER_POSTS=refresh;
  window.addEventListener('azaadLanguageChanged',refresh);
  window.addEventListener('azaadPublicContentLanguageChanged',refresh);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',async()=>{if(state.started)return;state.started=true;await load();},{once:true});else if(!state.started){state.started=true;load();}
})();
