(() => {
  'use strict';

  const SUPABASE_URL='https://derofsthjivlkcdnojww.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY='sb_publishable_GC253fvQebNBsDOaKjWGRw_tPYJrgLa';
  const PATIENTS_API=`${SUPABASE_URL}/functions/v1/azaad-patients`;
  const ADMIN_API=`${SUPABASE_URL}/functions/v1/azaad-admin`;
  const SESSION_KEY='azaad_admin_token';
  const state={patients:[],search:'',loading:false,initialized:false,authListenerBound:false,bookings:[],bookingDate:''};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const date=v=>{if(!v)return '—';const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('ar-EG',{year:'numeric',month:'short',day:'numeric'});};
  const money=v=>{const n=Number(v);return Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';};
  const toast=(m,error=false)=>{if(typeof window.showToast==='function'){window.showToast(m,error?'error':'success');return}let t=$('patientsToast');if(!t){t=document.createElement('div');t.id='patientsToast';t.className='toast';document.body.appendChild(t)}t.textContent=m;t.style.background=error?'#a32939':'#17214f';t.classList.add('show');clearTimeout(window.__patientsToastTimer);window.__patientsToastTimer=setTimeout(()=>t.classList.remove('show'),3500)};
  function token(){const live=window.AZAAD?.state?.session?.access_token;if(live){try{sessionStorage.setItem(SESSION_KEY,live)}catch(_){ }return live}try{return sessionStorage.getItem(SESSION_KEY)||''}catch(_){return ''}}
  async function api(url,options={}){const t=token();if(!t)throw new Error('جلسة الإدارة غير موجودة أو منتهية.');const r=await fetch(url,{...options,cache:'no-store',headers:{Accept:'application/json',Authorization:`Bearer ${t}`,apikey:SUPABASE_PUBLISHABLE_KEY,...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});let b={};try{b=await r.json()}catch(_){}if(!r.ok)throw new Error(b?.error||b?.message||`HTTP ${r.status}`);return b}
  function styles(){if($('patientsCenterStyles'))return;const s=document.createElement('style');s.id='patientsCenterStyles';s.textContent=`
    #patientsPanel .patient-tools{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;margin:15px 0}#patientsPanel .patient-card{border:1px solid #e2e6ef;border-radius:14px;padding:15px;background:#fff;margin-top:10px}#patientsPanel .patient-main{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:15px;align-items:center}#patientsPanel .patient-mrn{display:inline-flex;background:#eef1f8;color:#17214f;border-radius:999px;padding:5px 10px;font-weight:900;font-size:12px;direction:ltr}#patientsPanel .patient-name{font-size:17px;font-weight:900;color:#17214f;margin:7px 0 4px}#patientsPanel .patient-meta{color:#6c758c;font-size:12px;line-height:1.9}#patientsPanel .patient-actions{display:flex;gap:8px;flex-wrap:wrap}.patient-stats{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.patient-stat{background:#f7f8fb;border:1px solid #e8eaf0;border-radius:10px;padding:7px 10px;font-size:12px;color:#5f6880}.patient-warning{background:#fff8e6;color:#755c00;border:1px solid #f2df9a;border-radius:10px;padding:10px;margin-top:10px}.p360-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.p360-stat{background:#f7f8fb;border:1px solid #e8eaf0;border-radius:12px;padding:12px}.p360-list{display:grid;gap:8px}.p360-row{border:1px solid #e5e8ef;border-radius:10px;padding:10px}.appointment-center{border-top:1px solid #eee;margin-top:20px;padding-top:20px}.appointment-tools{display:grid;grid-template-columns:220px minmax(0,1fr) auto;gap:10px;margin:12px 0}.appointment-row{display:grid;grid-template-columns:120px minmax(0,1fr) 140px 140px auto;gap:10px;align-items:center;border:1px solid #e4e7ee;border-radius:10px;padding:10px}.appointment-row+.appointment-row{margin-top:8px}.p360-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:15px 0}.p360-tab{border:1px solid #d9deea;background:#fff;border-radius:20px;padding:8px 12px}.p360-tab.active{background:#17214f;color:#fff}.p360-content{min-height:120px}.patient-readonly{background:#f5f6f9!important;cursor:not-allowed}@media(max-width:800px){#patientsPanel .patient-tools,#patientsPanel .patient-main,.appointment-tools,.appointment-row{grid-template-columns:1fr}.p360-grid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
  function inject(){const tabs=document.querySelector('.tabs'),admin=$('adminPage');if(!tabs||!admin)return false;if(!$('patientsTab')){const t=document.createElement('button');t.id='patientsTab';t.className='tab';t.dataset.panel='patientsPanel';t.type='button';t.textContent='🤢 ملفات المرضى';tabs.insertBefore(t,tabs.firstElementChild);t.onclick=()=>activate('patientsPanel',t)}if(!$('patientsPanel')){const p=document.createElement('section');p.id='patientsPanel';p.className='panel';p.innerHTML=`<div class="card"><div class="panel-head"><div><h2>🤢 ملفات المرضى + Patient 360</h2><div class="muted">🆔 MRN ثابت — بيانات المريض، الحجوزات، الفواتير، المدفوعات والمتابعة في مكان واحد.</div></div><button id="refreshPatientsBtn" class="btn btn-secondary">🔄 تحديث</button></div><div class="patient-tools"><input id="patientSearchInput" type="search" placeholder="🔎 الاسم / الموبايل / MRN / البريد"><button id="clearPatientSearchBtn" class="btn btn-secondary">مسح</button></div><div id="patientsCount" class="muted"></div><div id="patientsList" class="items"><div class="empty">👥 اضغط تحديث.</div></div><div class="appointment-center"><div class="panel-head"><div><h3>📅 مواعيد المرضى</h3><div class="muted">اختر أي تاريخ — أمس، اليوم، غدًا أو بعد شهر — لعرض حجوزات ذلك اليوم.</div></div></div><div class="appointment-tools"><input id="bookingDateFilter" type="date"><input id="bookingSearch" placeholder="🔎 اسم / هاتف / MRN / رقم الحجز"><button id="bookingToday" class="btn btn-secondary">📅 اليوم</button></div><div id="appointmentList"><div class="empty">اختر تاريخًا.</div></div></div><div class="patient-warning">🔐 MRN لا يمكن تعديله. كل تعديل على اسم أو هاتف المريض يسجل في Audit Log.</div></div>`;admin.insertBefore(p,admin.querySelector('.panel'));$('refreshPatientsBtn').onclick=loadPatients;$('clearPatientSearchBtn').onclick=()=>{$('patientSearchInput').value='';state.search='';loadPatients()};$('patientSearchInput').oninput=e=>{state.search=e.target.value.trim().toLowerCase();renderPatients()};$('bookingDateFilter').value=today();$('bookingDateFilter').onchange=loadAppointments;$('bookingSearch').oninput=renderAppointments;$('bookingToday').onclick=()=>{$('bookingDateFilter').value=today();loadAppointments()}}return true}
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  function activate(id,tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));if(id==='patientsPanel'){loadPatients();loadAppointments()}}
  function filtered(){const q=state.search;if(!q)return state.patients;return state.patients.filter(p=>[p.mrn,p.patient_name,p.patient_phone,p.patient_phone_normalized,p.patient_email].filter(Boolean).join(' ').toLowerCase().includes(q))}
  function renderPatients(){const list=$('patientsList');if(!list)return;const rows=filtered();$('patientsCount').textContent=`👥 ${rows.length} ملف من أصل ${state.patients.length}`;if(!rows.length){list.innerHTML='<div class="empty">📭 لا توجد ملفات مطابقة.</div>';return}list.innerHTML=rows.map(p=>`<article class="patient-card"><div class="patient-main"><div><span class="patient-mrn">🆔 ${esc(p.mrn||'—')}</span><div class="patient-name">${esc(p.patient_name||'—')}</div><div class="patient-meta">📲 <span dir="ltr">${esc(p.patient_phone||'—')}</span>${p.patient_email?`<br>📧 ${esc(p.patient_email)}`:''}<br>🗓️ فتح الملف: ${esc(date(p.created_at))}</div></div><div class="patient-actions"><button class="btn btn-primary" data-p360="${esc(p.id)}">👤 Patient 360</button><button class="btn btn-secondary" data-edit="${esc(p.id)}">✍️ تعديل الاسم والموبايل</button></div></div><div class="patient-stats"><span class="patient-stat">📅 الحجوزات: <strong>${Number(p.booking_count||0)}</strong></span><span class="patient-stat">🕒 آخر موعد: ${esc(p.last_appointment||'—')}</span><span class="patient-stat">🚦 ${p.active===false?'🔴 غير نشط':'🟢 نشط'}</span></div></article>`).join('');list.querySelectorAll('[data-p360]').forEach(b=>b.onclick=()=>open360(b.dataset.p360));list.querySelectorAll('[data-edit]').forEach(b=>{const p=state.patients.find(x=>String(x.id)===String(b.dataset.edit));b.onclick=()=>p&&editPatient(p)})}
  async function loadPatients(){if(state.loading)return;state.loading=true;try{const q=encodeURIComponent(state.search||'');const r=await api(`${PATIENTS_API}?api=patients&search=${q}`);state.patients=Array.isArray(r?.patients)?r.patients:[];renderPatients()}catch(e){$('patientsList').innerHTML=`<div class="error">❌ ${esc(e.message)}</div>`;toast(e.message,true)}finally{state.loading=false}}
  async function loadAppointments(){const box=$('appointmentList');if(!box)return;box.innerHTML='<div class="empty">⏳ جاري تحميل مواعيد اليوم...</div>';try{const r=await api(`${ADMIN_API}?api=dashboard`);state.bookings=Array.isArray(r?.bookings)?r.bookings:[];renderAppointments()}catch(e){box.innerHTML=`<div class="error">❌ ${esc(e.message)}</div>`;toast(e.message,true)}}
  function renderAppointments(){const box=$('appointmentList');if(!box)return;const d=$('bookingDateFilter')?.value||today(),q=($('bookingSearch')?.value||'').trim().toLowerCase();const rows=state.bookings.filter(x=>String(x.appointment_date||'').slice(0,10)===d&&(!q||[x.booking_code,x.patient_name,x.patient_phone,x.mrn,x.patient_mrn].filter(Boolean).join(' ').toLowerCase().includes(q)));if(!rows.length){box.innerHTML=`<div class="empty">📭 لا توجد حجوزات بتاريخ ${esc(date(d))}.</div>`;return}box.innerHTML=rows.map(x=>`<div class="appointment-row"><strong>⏰ ${esc(String(x.appointment_time||'').slice(0,5)||'—')}</strong><div><b>🤢 ${esc(x.patient_name||'—')}</b><div class="muted">📲 ${esc(x.patient_phone||'—')} · 🆔 ${esc(x.mrn||x.patient_mrn||'—')} · 🔖 ${esc(x.booking_code||'—')}</div></div><span>${esc(x.doctor_name||x.doctor||'—')}</span><span>${esc(x.service_name||x.service||'—')}</span>${status(x.status)}</div>`).join('')}
  function status(s){const n=String(s||'').toLowerCase();return `<span class="badge ${n==='confirmed'?'confirmed':n==='cancelled'?'cancelled':n==='completed'?'completed':'pending'}">${esc(s||'—')}</span>`}
  async function open360(id){$('modalTitle').textContent='👤 Patient 360';$('modalContent').innerHTML='<div class="empty">⏳ جاري تحميل الملف الكامل...</div>';$('modal').classList.add('show');try{const r=await api(`${PATIENTS_API}?api=patient&id=${encodeURIComponent(id)}`);render360(r)}catch(e){$('modalContent').innerHTML=`<div class="error">❌ ${esc(e.message)}</div>`;toast(e.message,true)}}
  function render360(r){const p=r.patient||{},bs=r.bookings||[],ins=r.invoices||[],ps=r.payments||[],fs=r.followups||[];const unpaid=ins.filter(x=>['unpaid','pending','partial','overdue'].includes(String(x.status||'').toLowerCase())).length;$('modalContent').innerHTML=`<div><span class="patient-mrn">🆔 ${esc(p.mrn||'—')}</span><h2 style="margin:10px 0">🤢 ${esc(p.patient_name||'—')}</h2><div class="muted">📲 ${esc(p.patient_phone||'—')} ${p.patient_email?`· 📧 ${esc(p.patient_email)}`:''}</div></div><div class="p360-grid"><div class="p360-stat">📅 الحجوزات<br><strong>${bs.length}</strong></div><div class="p360-stat">🧾 الفواتير<br><strong>${ins.length}</strong></div><div class="p360-stat">💳 المدفوعات<br><strong>${ps.length}</strong></div><div class="p360-stat">⚠️ غير مدفوعة<br><strong>${unpaid}</strong></div></div>${(r.warnings||[]).length?`<div class="patient-warning">⚠️ ${r.warnings.map(esc).join('<br>')}</div>`:''}<div class="p360-tabs"><button class="p360-tab active" data-view="appointments">📅 المواعيد</button><button class="p360-tab" data-view="invoices">🧾 الفواتير</button><button class="p360-tab" data-view="payments">💳 المدفوعات</button><button class="p360-tab" data-view="followups">🔄 المتابعة</button></div><div id="p360Content" class="p360-content"></div>`;const views={appointments:bs,invoices:ins,payments:ps,followups:fs};const draw=k=>{document.querySelectorAll('.p360-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===k));const arr=views[k]||[];if(!arr.length){$('p360Content').innerHTML='<div class="empty">📭 لا توجد بيانات.</div>';return}$('p360Content').innerHTML=`<div class="p360-list">${arr.slice(0,100).map(x=>`<div class="p360-row">${k==='appointments'?`📅 ${esc(date(x.appointment_date))} ⏰ ${esc(String(x.appointment_time||'').slice(0,5))} · ${status(x.status)}<br>🔖 ${esc(x.booking_code||x.id||'—')}`:k==='invoices'?`🧾 ${esc(x.invoice_number||x.id||'—')} · ${money(x.total_amount??x.amount)} · ${esc(x.status||'—')}`:k==='payments'?`💳 ${money(x.amount)} · ${esc(x.payment_method||x.method||'—')} · ${esc(x.payment_date||x.created_at||'—')}`:`🔄 ${esc(x.followup_date||x.next_date||x.created_at||'—')} · ${esc(x.status||'—')}`}</div>`).join('')}</div>`};document.querySelectorAll('.p360-tab').forEach(b=>b.onclick=()=>draw(b.dataset.view));draw('appointments')}
  function editPatient(p){$('modalTitle').textContent='✍️ تعديل ملف المريض';$('modalContent').innerHTML=`<form id="patientEditForm"><div class="grid"><label class="full">🆔 MRN<input class="patient-readonly" disabled readonly value="${esc(p.mrn||'')}"><small class="muted">🔐 MRN ثابت مدى الحياة.</small></label><label>🤢 الاسم<input id="editPatientName" required value="${esc(p.patient_name||'')}"></label><label>📲 الموبايل<input id="editPatientPhone" required value="${esc(p.patient_phone||'')}"></label></div><div class="patient-warning">📝 سيتم تسجيل التعديل في Audit Log وتحديث الحجوزات المرتبطة.</div><div class="modal-actions"><button class="btn btn-primary">💾 حفظ</button><button type="button" id="cancelPatientEdit" class="btn btn-secondary">إلغاء</button></div></form>`;$('modal').classList.add('show');$('cancelPatientEdit').onclick=()=>window.closeModal?.();$('patientEditForm').onsubmit=async e=>{e.preventDefault();try{const r=await api(`${PATIENTS_API}?api=patient`,{method:'PUT',body:JSON.stringify({id:p.id,patient_name:$('editPatientName').value.trim(),patient_phone:$('editPatientPhone').value.trim()})});const i=state.patients.findIndex(x=>String(x.id)===String(p.id));if(i>=0)state.patients[i]={...state.patients[i],...r.patient};window.closeModal?.();renderPatients();toast('✅ تم تحديث ملف المريض.')}catch(err){toast(err.message,true)}}}
  function bind(){const s=window.AZAAD?.supabase;if(!s?.auth||state.authListenerBound)return;state.authListenerBound=true;s.auth.onAuthStateChange((event,session)=>{if(session?.access_token){try{sessionStorage.setItem(SESSION_KEY,session.access_token)}catch(_){}if(event==='TOKEN_REFRESHED'||event==='SIGNED_IN')setTimeout(()=>{loadPatients();loadAppointments()},0)}else if(event==='SIGNED_OUT'){state.patients=[];state.bookings=[];renderPatients();renderAppointments()}})}
  async function init(){if(state.initialized)return;try{if(window.AZAAD_AUTH_READY?.then)await window.AZAAD_AUTH_READY}catch(_){}styles();if(!inject())return;state.initialized=true;bind();if(token()){loadPatients();loadAppointments()}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.AZAAD_PATIENTS={init,load:loadPatients,refresh:loadPatients,get patients(){return [...state.patients]},get state(){return {...state,patients:[...state.patients]}}};
})();
