(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const isEnglish = () => String(document.documentElement.lang || '').toLowerCase().startsWith('en');
  const tr = (ar,en) => isEnglish() ? en : ar;
  const normalizePatientNumber = value => { const v=String(value||'').trim().toUpperCase(); if(/^AZA-\d{6}$/.test(v))return v; if(/^AZA\d{6}$/.test(v))return `AZA-${v.slice(3)}`; if(/^\d{1,6}$/.test(v))return `AZA-${v.padStart(6,'0')}`; return ''; };
  const displayPatientNumber = mrn => { const n=normalizePatientNumber(mrn); return n ? `Patient ${n.slice(4)}` : tr('ملف المريض —','Patient —'); };
  async function api(url, options={}) { const r=await fetch(url,{...options,credentials:'include',cache:'no-store',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}}); let b={}; try{b=await r.json()}catch(_){} if(!r.ok)throw Error(b?.error||b?.message||`HTTP ${r.status}`); return b; }
  const state={patients:[],search:'',loading:false};
  function ensurePanel(){const tabs=document.querySelector('.tabs'),admin=$('adminPage');if(!tabs||!admin)return null;let tab=$('patientsTab');if(!tab){tab=document.createElement('button');tab.id='patientsTab';tab.className='tab';tab.type='button';tab.dataset.panel='patientsPanel';tab.textContent=tr('👥 ملفات المرضى','👥 Patients');tabs.insertBefore(tab,tabs.firstElementChild);}let panel=$('patientsPanel');if(!panel){panel=document.createElement('section');panel.id='patientsPanel';panel.className='panel';panel.innerHTML=`<div class="card"><div class="panel-head"><div><h2>${tr('👥 ملفات المرضى + Patient 360','👥 Patients + Patient 360')}</h2><div class="muted">${tr('المصدر الموحد: Appwrite session → Vercel API → Neon.','Canonical source: Appwrite session → Vercel API → Neon.')}</div></div><button id="refreshPatientsBtn" class="btn btn-secondary">🔄 ${tr('تحديث','Refresh')}</button></div><div style="display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;margin:15px 0"><input id="patientSearchInput" type="search" placeholder="🔎 ${tr('الاسم / الموبايل / رقم الملف','Name / Phone / Patient Number')}"><button id="clearPatientSearchBtn" class="btn btn-secondary">${tr('مسح','Clear')}</button></div><div id="patientsCount" class="muted"></div><div id="patientsList" class="items"><div class="empty">${tr('جاري التحميل…','Loading…')}</div></div><div id="patient360" hidden></div></div>`;admin.insertBefore(panel,admin.querySelector('.panel'));}return panel;}
  function render(){const list=$('patientsList');if(!list)return;const q=state.search.toLowerCase();const rows=state.patients.filter(p=>!q||[p.mrn,displayPatientNumber(p.mrn),p.patient_name,p.patient_phone,p.patient_email].filter(Boolean).join(' ').toLowerCase().includes(q));$('patientsCount').textContent=`👥 ${rows.length} / ${state.patients.length}`;if(!rows.length){list.innerHTML=`<div class="empty">${tr('لا توجد ملفات مطابقة.','No matching patients.')}</div>`;return;}list.innerHTML=rows.map(p=>`<article style="border:1px solid #e2e6ef;border-radius:14px;padding:15px;margin-top:10px"><div style="display:flex;justify-content:space-between;gap:15px;align-items:center;flex-wrap:wrap"><div><span>🆔 ${esc(displayPatientNumber(p.mrn))}</span><div style="font-weight:900;font-size:17px;margin-top:7px">${esc(p.patient_name||'—')}</div><div class="muted">📲 ${esc(p.patient_phone||'—')} ${p.patient_email?` · 📧 ${esc(p.patient_email)}`:''}</div><div class="muted">📅 ${tr('الحجوزات','Appointments')}: ${Number(p.booking_count||0)} · ${tr('آخر موعد','Last')}: ${esc(p.last_appointment||'—')}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary" data-p360="${esc(p.id)}">👤 ${tr('فتح الملف','Open Patient')}</button><button class="btn btn-secondary" data-edit="${esc(p.id)}">✍️ ${tr('تعديل','Edit')}</button></div></div></article>`).join('');list.querySelectorAll('[data-p360]').forEach(b=>b.onclick=()=>open360(b.dataset.p360));list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPatient(state.patients.find(p=>String(p.id)===String(b.dataset.edit))));}
  async function loadPatients(){if(state.loading)return;state.loading=true;try{const q=encodeURIComponent(normalizePatientNumber(state.search)||state.search);const r=await api(`/api/admin-appointments?api=patients&search=${q}`);state.patients=Array.isArray(r.patients)?r.patients:[];render();}catch(e){const list=$('patientsList');if(list)list.innerHTML=`<div class="error">❌ ${esc(e.message)}</div>`;}finally{state.loading=false;}}
  async function open360(id){const box=$('patient360');if(!box)return;box.hidden=false;box.innerHTML=`<div class="loading">⏳ ${tr('جاري تحميل Patient 360…','Loading Patient 360…')}</div>`;try{const r=await api(`/api/admin-appointments?api=patient&id=${encodeURIComponent(id)}`);const p=r.patient||{};box.innerHTML=`<div class="card" style="margin-top:15px"><div class="panel-head"><h3>👤 ${esc(p.patient_name||'—')} · ${esc(displayPatientNumber(p.mrn))}</h3><button class="btn btn-secondary" id="close360">✕</button></div><div class="muted">📅 ${tr('حجوزات','Appointments')}: ${r.summary?.booking_count||0} · 🩺 ${tr('زيارات','Visits')}: ${r.summary?.visit_count||0} · 🧾 ${tr('فواتير','Invoices')}: ${r.summary?.invoice_count||0} · 💰 ${tr('الرصيد','Balance')}: ${Number(r.summary?.balance||0).toFixed(2)}</div><div style="margin-top:15px"><h4>${tr('التاريخ السريري','Clinical history')}</h4>${(r.visits||[]).map(v=>`<div style="border:1px solid #e5e8ef;border-radius:10px;padding:10px;margin-top:8px"><strong>${esc(v.visit_date||'—')} ${esc(v.visit_type||'')}</strong><div>${esc(v.assessment||v.clinical_notes||'—')}</div></div>`).join('')||`<div class="empty">${tr('لا توجد زيارات مسجلة.','No visits recorded.')}</div>`}</div></div>`;$('close360').onclick=()=>{box.hidden=true;box.innerHTML='';};}catch(e){box.innerHTML=`<div class="error">❌ ${esc(e.message)}</div>`;}}
  async function editPatient(p){if(!p)return;const name=prompt(tr('اسم المريض:','Patient name:'),p.patient_name||'');if(name===null)return;const phone=prompt(tr('رقم الهاتف:','Phone:'),p.patient_phone||'');if(phone===null)return;try{await api(`/api/admin-appointments?api=patient&id=${encodeURIComponent(p.id)}`,{method:'PUT',body:JSON.stringify({patient_name:name.trim(),patient_phone:phone.trim()})});await loadPatients();}catch(e){alert(e.message);}}
  function init(){if(!ensurePanel())return;const b=$('refreshPatientsBtn');if(b)b.onclick=loadPatients;const input=$('patientSearchInput');if(input)input.oninput=e=>{state.search=e.target.value.trim();loadPatients();};const clear=$('clearPatientSearchBtn');if(clear)clear.onclick=()=>{state.search='';if(input)input.value='';loadPatients();};const tab=$('patientsTab');if(tab)tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='patientsPanel'));loadPatients();};loadPatients();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
