(() => {
  'use strict';
  const MAPS_URL='https://maps.app.goo.gl/6kta6eBxN7TH88ATA?g_st=ic';
  const DEFAULT_WHATSAPP='201140526294';
  const LANGUAGE_KEY='azaadClinicLanguage';
  const $=id=>document.getElementById(id);
  const normalizeDigits=value=>String(value||'').replace(/\D/g,'');
  const getPublicData=()=>window.AZAAD_PUBLIC_CLINIC_DATA||{};
  const getSettings=()=>getPublicData().settings||{};
  const central=()=>window.AZAAD_I18N;
  const language=()=>central()?.language?.() || (localStorage.getItem(LANGUAGE_KEY)==='en'?'en':'ar');
  function setting(...keys){for(const key of keys){const value=getSettings()?.[key];if(value!==undefined&&value!==null&&String(value).trim())return String(value).trim();}return ''}
  const getWhatsApp=()=>normalizeDigits(setting('whatsapp','whatsapp_number','whatsapp_phone','phone_whatsapp')||DEFAULT_WHATSAPP);
  const getPhone=()=>setting('phone','phone_number','clinic_phone','contact_phone');
  const getEmail=()=>setting('email','clinic_email','contact_email');
  const getAddress=()=>{const ar=setting('address','clinic_address','location','clinic_location')||'دمياط - شارع نافع، مقابل مسجد المظلوم - أعلى صيدلية الرياض';if(language()!=='en') return ar;return setting('address_en','clinic_address_en','location_en','clinic_location_en')||'Damietta - Nafea Street, opposite Al-Mazloum Mosque, above Al-Riyad Pharmacy';};
  const getSocial=()=>({facebook:setting('facebook_url','facebook','facebookUrl'),instagram:setting('instagram_url','instagram','instagramUrl'),linkedin:setting('linkedin_url','linkedin','linkedinUrl'),tiktok:setting('tiktok_url','tiktok','tiktokUrl')});
  const whatsappIcon='<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M20.52 3.48A11.84 11.84 0 0 0 12.05 0C5.5 0 .17 5.33.17 11.89c0 2.1.55 4.15 1.59 5.95L.07 24l6.3-1.65a11.9 11.9 0 0 0 5.67 1.44h.01c6.55 0 11.88-5.33 11.88-11.9 0-3.17-1.23-6.15-3.41-8.41ZM12.05 21.77h-.01a9.86 9.86 0 0 1-5.03-1.37l-.36-.21-3.74.98 1-3.65-.23-.37a9.88 9.88 0 0 1-1.51-5.26C2.17 6.43 6.6 2 12.06 2a9.86 9.86 0 0 1 7.02 2.92 9.89 9.89 0 0 1 2.9 7.04c0 5.46-4.44 9.89-9.93 9.81Zm5.43-7.4c-.3-.15-1.78-.88-2.05-.98-.28-.1-.48-.15-.69.15-.2.3-.79.98-.97 1.18-.18.2-.36.23-.66.08-.3-.15-1.26-.46-2.4-1.48-.89-.79-1.49-1.76-1.67-2.06-.18-.3-.02-.46.13-.61.14-.14.3-.36.45-.54.15-.18.2-.3.3-.5.1-.2.05-.38-.03-.53-.08-.15-.69-1.66-.94-2.28-.25-.6-.5-.52-.69-.53h-.59c-.2 0-.53.08-.81.38-.28.3-1.06 1.04-1.06 2.54 0 1.5 1.09 2.94 1.24 3.14.15.2 2.14 3.27 5.18 4.58.72.31 1.29.5 1.73.64.73.23 1.39.2 1.91.12.58-.09 1.78-.73 2.03-1.44.25-.71.25-1.32.18-1.44-.07-.13-.27-.2-.57-.35Z"/></svg>';
  const socialMarkup=(social,compact=false)=>{
    const whatsapp=getWhatsApp();
    const items=[
      ['facebook','f','Facebook','#1877F2'],
      ['instagram','◎','Instagram','#E4405F'],
      ['linkedin','in','LinkedIn','#0A66C2'],
      ['tiktok','♪','TikTok','#000000']
    ];
    const socialHtml=items.filter(([key])=>social[key]).map(([key,icon,label,color])=>`<a class="azaad-social${compact?' azaad-social-hero':''}" href="${social[key]}" target="_blank" rel="noopener noreferrer" aria-label="${label}" title="${label}" style="--social-brand:${color}">${icon}</a>`).join('');
    const wa=`<a id="waHero" class="azaad-social${compact?' azaad-social-hero':''} azaad-social-whatsapp" href="https://wa.me/${whatsapp}" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" title="WhatsApp" style="--social-brand:#25D366">${whatsappIcon}</a>`;
    return socialHtml+wa;
  };
  function injectFooterStyles(){
    if(document.getElementById('azaad-footer-styles'))return;
    const style=document.createElement('style');style.id='azaad-footer-styles';style.textContent=`
      .azaad-hero-socials{display:flex;align-items:center;justify-content:flex-start;gap:10px;margin-top:10px;direction:ltr}
      .hero-social-block{display:flex;flex-direction:column;align-items:flex-start;margin-top:14px}
      .hero-social-title{font-size:13px;font-weight:700;color:var(--navy,#101b56);line-height:1.7;margin-bottom:2px}
      .azaad-social{width:42px;height:42px;border:0;border-radius:8px;display:inline-flex;align-items:center;justify-content:center;color:#fff;background:var(--social-brand,#101b56);font-weight:800;font-size:17px;line-height:1;transition:transform .2s ease,filter .2s ease,box-shadow .2s ease}
      .azaad-social svg{width:23px;height:23px;display:block}
      .azaad-social:hover{transform:translateY(-2px);filter:brightness(.96);box-shadow:0 8px 20px color-mix(in srgb,var(--social-brand) 28%,transparent)}
      .azaad-social-hero{width:42px;height:42px;border-radius:8px;font-size:16px;box-shadow:0 4px 14px color-mix(in srgb,var(--social-brand) 22%,transparent)}
      .azaad-social-hero:hover{background:var(--social-brand);filter:brightness(.94);box-shadow:0 8px 18px color-mix(in srgb,var(--social-brand) 36%,transparent)}
      .azaad-footer{background:#fff;color:var(--navy,#101b56);padding:48px 0 24px;border-top:1px solid var(--line,#e5e3ea)}
      .azaad-footer-grid{display:grid;grid-template-columns:1.35fr 1fr 1fr;gap:34px;align-items:start}
      .azaad-footer-brand .logo{display:block;margin-bottom:8px;color:var(--az-navy,var(--navy,#101b56))}
      .azaad-footer-brand .logo span{color:var(--az-coral,var(--gold,#b88b3a))}
      .azaad-footer-tagline{margin:0;color:var(--muted,#687089);font-size:14px;max-width:330px}
      .azaad-socials{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px;direction:ltr}
      .azaad-footer .azaad-social{color:#fff;background:var(--social-brand)}
      .azaad-footer-title{margin:0 0 13px;color:var(--navy,#101b56);font-size:16px;font-weight:800}
      .azaad-footer-list{display:grid;gap:9px;margin:0;padding:0;list-style:none}
      .azaad-footer-list a,.azaad-footer-contact{color:var(--muted,#687089);font-size:13px;line-height:1.8;overflow-wrap:anywhere}
      .azaad-footer-list a:hover,.azaad-footer-contact a:hover{color:var(--navy,#101b56)}
      .azaad-footer-contact{display:flex;gap:8px;align-items:flex-start;margin:0 0 8px}
      .azaad-footer-contact strong{color:var(--navy,#101b56);font-size:13px}
      .azaad-footer-bottom{margin-top:34px;padding-top:18px;border-top:1px solid var(--line,#e5e3ea);display:flex;justify-content:space-between;gap:18px;color:var(--muted,#687089);font-size:12px}
      @media(max-width:800px){.azaad-footer-grid{grid-template-columns:1fr 1fr}.azaad-footer-brand{grid-column:1/-1}}
      @media(max-width:560px){.azaad-footer{padding:38px 0 20px}.azaad-footer-grid{grid-template-columns:1fr;gap:25px}.azaad-footer-brand{grid-column:auto}.azaad-footer-bottom{flex-direction:column;gap:5px}.azaad-hero-socials{justify-content:center}.hero-social-block{align-items:center;width:100%}.hero-social-title{text-align:center}}
    `;document.head.appendChild(style);
  }
  function mergeContactIntoFooter(){const duplicateContact=document.querySelector('main > #contact');const footer=document.querySelector('footer');if(!footer)return;if(duplicateContact)duplicateContact.remove();footer.id='contact';}
  function renderFooter(){const footer=document.querySelector('footer');if(!footer)return;mergeContactIntoFooter();injectFooterStyles();const lang=language(),social=getSocial();const labels=lang==='en'?{quick:'Quick Links',contact:'Contact Us',phone:'Phone',email:'Email',address:'Clinic Address',home:'Home',about:'About Us',services:'Services',doctors:'Doctors',booking:'Book an Appointment',contactLink:'Contact Us',tagline:'Mental health and psychotherapy',rights:'All rights reserved.',maps:'Open location on Google Maps',share:'Share clinic website'}:{quick:'روابط سريعة',contact:'تواصل معنا',phone:'الهاتف',email:'البريد الإلكتروني',address:'عنوان العيادة',home:'الرئيسية',about:'عن العيادة',services:'الخدمات',doctors:'الأطباء',booking:'حجز موعد',contactLink:'تواصل معنا',tagline:'للصحة النفسية والعلاج النفسي',rights:'جميع الحقوق محفوظة.',maps:'فتح الموقع على Google Maps',share:'مشاركة الموقع الإلكتروني للعيادة'};const socialItems=socialMarkup(social);const phone=getPhone(),email=getEmail(),address=getAddress(),whatsapp=getWhatsApp();const waUrl=`https://wa.me/${whatsapp}?text=${encodeURIComponent(lang==='en'?'Hello Azaad Clinic, I would like to ask about an appointment.':'مرحبًا عيادة أزاد، أود الاستفسار عن حجز موعد.')}`;footer.className='azaad-footer';footer.innerHTML=`<div class="container"><div class="azaad-footer-grid"><div class="azaad-footer-brand"><div class="logo">AZAAD <span>PSYCHOTHERAPY</span></div><p class="azaad-footer-tagline">${setting('tagline','tagline_ar')||labels.tagline}</p><div class="azaad-socials" aria-label="Social media">${socialItems}</div></div><div><h3 class="azaad-footer-title">${labels.quick}</h3><ul class="azaad-footer-list"><li><a href="#home">${labels.home}</a></li><li><a href="#about">${labels.about}</a></li><li><a href="#services">${labels.services}</a></li><li><a href="#doctors">${labels.doctors}</a></li><li><a href="#booking">${labels.booking}</a></li><li><a href="#contact">${labels.contactLink}</a></li></ul></div><div><h3 class="azaad-footer-title">${labels.contact}</h3><p class="azaad-footer-contact"><strong>${labels.phone}:</strong><a href="${phone?`tel:${phone.replace(/[^\d+]/g,'')}`:'#contact'}">${phone||'—'}</a></p><p class="azaad-footer-contact"><strong>${labels.email}:</strong><a href="${email?`mailto:${email}`:'#contact'}">${email||'—'}</a></p><p class="azaad-footer-contact"><strong>${labels.address}:</strong><span>${address||'—'}</span></p><p class="azaad-footer-contact"><strong>WhatsApp:</strong><a href="${waUrl}" target="_blank" rel="noopener noreferrer">${lang==='en'?'Start chat':'ابدأ المحادثة'}</a></p><p class="azaad-footer-contact"><strong>${labels.address}:</strong><a href="${MAPS_URL}" target="_blank" rel="noopener noreferrer">${labels.maps}</a></p></div></div><div class="azaad-footer-bottom"><span>© <span id="year"></span> Azaad Psychotherapy</span><span>${labels.rights}</span></div></div>`;const year=$('year');if(year)year.textContent=String(new Date().getFullYear());}
  function renderHeroSocials(){const container=$('heroSocials');if(!container)return;injectFooterStyles();const social=getSocial();container.innerHTML=socialMarkup(social,true);container.setAttribute('aria-label',language()==='en'?'Clinic social media':'وسائل التواصل الاجتماعي للعيادة');}
  function closeMobileMenu(){const nav=$('nav'),menu=$('menu');if(!nav)return;nav.classList.remove('mobile-open');if(menu){menu.setAttribute('aria-expanded','false');menu.textContent='☰'}}
  function setupMobileMenu(){const nav=$('nav'),menu=$('menu');if(!nav||!menu||menu.dataset.publicUiMenuBound==='true')return;menu.dataset.publicUiMenuBound='true';menu.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const open=nav.classList.toggle('mobile-open');menu.setAttribute('aria-expanded',open?'true':'false');menu.textContent=open?'✕':'☰'});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMobileMenu));window.addEventListener('resize',()=>{if(window.innerWidth>900)closeMobileMenu()})}
  function updateContactLinks(){const whatsapp=getWhatsApp(),phone=getPhone(),email=getEmail(),address=getAddress(),lang=language();const phoneLink=$('phoneLink'),phoneText=$('contactPhone'),emailLink=$('emailLink'),emailText=$('contactEmail'),waLink=$('waLink'),waHero=$('waHero'),mapsLink=$('mapsLink'),shareLocation=$('shareLocation'),addressElement=$('address');if(phoneText)phoneText.textContent=phone||'—';if(emailText)emailText.textContent=email||'—';if(addressElement){addressElement.textContent=address;addressElement.setAttribute('data-i18n','clinicAddress')}if(phoneLink)phoneLink.href=phone?`tel:${phone.replace(/[^\d+]/g,'')}`:'#contact';if(emailLink)emailLink.href=email?`mailto:${email}`:'#contact';const waMessage=lang==='en'?'Hello Azaad Clinic, I would like to ask about an appointment.':'مرحبًا عيادة أزاد، أود الاستفسار عن حجز موعد.';const waUrl=`https://wa.me/${whatsapp}?text=${encodeURIComponent(waMessage)}`;if(waLink)waLink.href=waUrl;if(waHero)waHero.href=waUrl;if(mapsLink){mapsLink.href=MAPS_URL;mapsLink.target='_blank';mapsLink.rel='noopener noreferrer'}if(shareLocation&&shareLocation.dataset.publicShareBound!=='true'){shareLocation.dataset.publicShareBound='true';shareLocation.addEventListener('click',async event=>{event.preventDefault();event.stopImmediatePropagation();const pageUrl=`${window.location.origin}${window.location.pathname}${window.location.search}`;const title=central()?.t?.('shareDataTitle')||(lang==='en'?'Azaad Clinic | Mental Health Clinic':'Azaad Clinic | عيادة آزاد للصحة النفسية');const text=central()?.t?.('shareDataText')||(lang==='en'?'🌐 Share Azaad Clinic website':'🌐 مشاركة الموقع الإلكتروني للعيادة');try{if(typeof navigator.share==='function'){await navigator.share({title,text,url:pageUrl});return}}catch(error){if(error?.name==='AbortError')return}try{await navigator.clipboard?.writeText(pageUrl);const message=central()?.t?.('copied')||(lang==='en'?'The clinic website link has been copied.':'تم نسخ رابط موقع العيادة الإلكتروني.');if(typeof window.alert==='function')window.alert(message);return}catch(_){const promptText=central()?.t?.('prompt')||(lang==='en'?'Copy the clinic website link:':'انسخ رابط موقع العيادة الإلكتروني:');if(typeof window.prompt==='function')window.prompt(promptText,pageUrl)}},{passive:false})}}
  function syncFromCentral(){const lang=language();document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-lang]').forEach(button=>{const active=button.getAttribute('data-lang')===lang;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active?'true':'false')});const menu=$('menu');if(menu)menu.setAttribute('aria-label',lang==='ar'?'القائمة':'Menu');updateContactLinks();renderHeroSocials();renderFooter()}
  function bindCentralLanguageButtons(){if(document.documentElement.dataset.centralLanguageCaptureBound==='true')return;document.documentElement.dataset.centralLanguageCaptureBound='true';document.addEventListener('click',event=>{const button=event.target?.closest?.('[data-lang]');if(!button)return;const target=button.getAttribute('data-lang');if(target!=='ar'&&target!=='en')return;event.preventDefault();event.stopImmediatePropagation();const c=central();if(typeof c?.setLanguage==='function')c.setLanguage(target);else localStorage.setItem(LANGUAGE_KEY,target);window.dispatchEvent(new CustomEvent('azaadLanguageChanged',{detail:{language:target}}))},true)}
  function setupCentralLanguage(){bindCentralLanguageButtons();syncFromCentral();window.addEventListener('azaadLanguageChanged',syncFromCentral);window.addEventListener('azaadPublicContentLanguageChanged',syncFromCentral)}
  function refreshPublicSettings(attempt=0){updateContactLinks();renderHeroSocials();renderFooter();if(attempt>=10)return;if(!window.AZAAD_PUBLIC_CLINIC_DATA)window.setTimeout(()=>refreshPublicSettings(attempt+1),500)}
  function initialize(){setupMobileMenu();setupCentralLanguage();refreshPublicSettings();window.addEventListener('azaadPublicClinicDataChanged',()=>refreshPublicSettings());window.addEventListener('load',()=>refreshPublicSettings());}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize);else initialize();
})();