/* AZAAD CLINIC — Scheduling V2 */
(function () {
  'use strict';
  const S = { date: new Date().toISOString().slice(0,10), view:'day', doctorId:'', doctors:[], services:[], bookings:[], schedules:[], overrides:[], waiting:[] };
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const iso = d => d.toISOString().slice(0,10);
  const t = v => String(v || '').slice(0,5);
  const toast = (m,err=false) => { const x=document.createElement('div'); x.textContent=m; x.style.cssText=`position:fixed;z-index:99999;bottom:20px;left:20px;right:20px;max-width:650px;margin:auto;padding:13px 17px;border-radius:10px;background:${err?'#a32939':'#17214f'};color:#fff;text-align:center`; document.body.appendChild(x); setTimeout(()=>x.remove(),3200); };
  const client = () => window.AZAAD?.supabase || null;
  async function db(table,columns='*',filter){ const c=client(); if(!c) throw Error('Supabase client غير متاح.'); let q=c.from(table).select(columns); if(filter) q=filter(q); const {data,error}=await q; if(error) throw error; return data||[]; }
  async function invoke(action,body){ const c=client(); if(!c) throw Error('Supabase client غير متاح.'); const {data,error}=await c.functions.invoke('azaad-appointments-actions',{body:{action,...body}}); if(error) throw error; if(data?.error) throw Error(data.error); return data; }
  function range(){ const d=new Date(`${S.date}T12:00:00`); if(S.view==='month'){return [iso(new Date(d.getFullYear(),d.getMonth(),1)),iso(new Date(d.getFullYear(),d.getMonth()+1,0))];} if(S.view==='week'){const a=new Date(d);a.setDate(d.getDate()-d.getDay());const b=new Date(a);b.setDate(a.getDate()+6);return[iso(a),iso(b)];} return[S.date,S.date]; }
  function labelDate(v){return new Intl.DateTimeFormat('ar-EG',{weekday:'long',day:'numeric',month:'long'}).format(new Date(`${v}T12:00:00`));}
  function to12(v){const [h,m]=t(v).split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`;}
  function minutes(v){const [h,m]=t(v).split(':').map(Number);return h*60+m;}
  function hhmm(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
  function root(){ if($('azaadSchedulingV2')) return $('azaadSchedulingV2'); const tabs=document.querySelector('.tabs'); const tab=document.createElement('button'); tab.className='tab';tab.type='button';tab.textContent='📅 Schedule V2';tabs?.appendChild(tab); const r=document.createElement('section');r.id='azaadSchedulingV2';r.className='panel';r.innerHTML=`<div class="card"><div class="panel-head"><div><h2>📅 Central Scheduling</h2><div class="muted">🧑‍⚕️ الطبيب • 🟢 متاح • 🔵 مؤكد • 🟡 انتظار • 🟠 No-show • 🔴 ملغي</div></div><div class="top-actions"><button id="sv2Today" class="btn btn-secondary">📅 اليوم</button><button id="sv2Refresh" class="btn btn-secondary">🔄 تحديث</button></div></div><div class="filters" style="grid-template-columns:150px 1fr 220px 160px"><select id="sv2View"><option value="day">يوم</option><option value="week">أسبوع</option><option value="month">شهر</option></select><input id="sv2Date" type="date"><select id="sv2Doctor"><option value="">كل الأطباء</option></select><button id="sv2Add" class="btn btn-primary">➕ إضافة موعد</button></div><div id="sv2Grid"></div></div><div class="card"><div class="panel-head"><div><h2>⏳ Waiting List</h2><div class="muted">Patient Identity + Doctor + Service + Priority</div></div><button id="sv2WaitingAdd" class="btn btn-primary">➕ إضافة انتظار</button></div><div id="sv2Waiting"></div></div>`;document.querySelector('#bookings')?.parentElement?.appendChild(r);$('sv2Date').value=S.date;$('sv2View').value=S.view; tab.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');r.classList.add('active');refresh();};$('sv2Date').onchange=()=>{S.date=$('sv2Date').value||S.date;refresh()};$('sv2View').onchange=()=>{S.view=$('sv2View').value;refresh()};$('sv2Doctor').onchange=()=>{S.doctorId=$('sv2Doctor').value;render()};$('sv2Today').onclick=()=>{S.date=new Date().toISOString().slice(0,10);$('sv2Date').value=S.date;refresh()};$('sv2Refresh').onclick=refresh;$('sv2Add').onclick=()=>bookingModal();$('sv2WaitingAdd').onclick=()=>waitingModal();return r; }
  async function refresh(){root();const [from,to]=range();try{S.doctors=await db('clinic_doctors','id,name,title,image_url,active',q=>q.eq('active',true).order('sort_order'));S.services=await db('clinic_services','id,name,duration_minutes,active',q=>q.eq('active',true).order('sort_order'));S.bookings=await db('clinic_bookings','id,booking_code,doctor_id,service_id,patient_id,patient_name,patient_phone,appointment_date,appointment_time,status,mode,notes',q=>q.gte('appointment_date',from).lte('appointment_date',to));S.schedules=await db('doctor_weekly_schedules','doctor_id,weekday,enabled,start_time,end_time,break_start,break_end,slot_minutes,buffer_minutes,max_daily_bookings');S.overrides=await db('doctor_schedule_overrides','doctor_id,override_date,type,start_time,end_time,break_start,break_end,slot_minutes,max_daily_bookings',q=>q.gte('override_date',from).lte('override_date',to));S.waiting=await db('clinic_waiting_list','id,patient_id,doctor_id,preferred_doctor_id,alternative_doctor_ids,service_id,requested_date,preferred_start_time,preferred_end_time,priority,reason,patient_phone_snapshot,status,position,source,notes,created_at',q=>q.in('status',['waiting','pending','active']).order('position',{ascending:true}));const ds=$('sv2Doctor');ds.innerHTML='<option value="">كل الأطباء</option>'+S.doctors.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');ds.value=S.doctorId;render();}catch(e){$('sv2Grid').innerHTML=`<div class="error">⚠️ تعذر تحميل الجدول: ${esc(e.message||e)}</div>`;console.error(e);}}
  function schedule(doctor,date){const d=new Date(`${date}T12:00:00`);const o=S.overrides.find(x=>String(x.doctor_id)===String(doctor)&&x.override_date===date);if(o)return o.type==='closed'?null:o;return S.schedules.find(x=>String(x.doctor_id)===String(doctor)&&Number(x.weekday)===d.getDay()&&x.enabled!==false)||null;}
  function slots(doctor,date){const s=schedule(doctor,date);if(!s)return[];let cur=minutes(s.start_time),end=minutes(s.end_time),step=Number(s.slot_minutes||30),bs=s.break_start?minutes(s.break_start):null,be=s.break_end?minutes(s.break_end):null,out=[];while(cur<end){if(bs===null||be===null||cur<bs||cur>=be)out.push(hhmm(cur));cur+=step+Number(s.buffer_minutes||0)}return out;}
  function badge(s){return({confirmed:'🔵 مؤكد',pending:'🟡 قيد التأكيد',cancelled:'🔴 ملغي',completed:'✅ مكتمل',no_show:'🟠 No-show'})[String(s||'').toLowerCase()]||'🟡 غير محدد';}
  function render(){const g=$('sv2Grid');if(!g)return;if(S.view==='month')return month(g);if(S.view==='week')return week(g);g.innerHTML=`<div class="muted">📅 ${esc(labelDate(S.date))}</div>`+S.doctors.filter(d=>!S.doctorId||String(d.id)===String(S.doctorId)).map(d=>doctorDay(d,S.date)).join('');waitingRender();}
  function doctorDay(d,date){const ss=slots(d.id,date),bs=S.bookings.filter(b=>String(b.doctor_id)===String(d.id)&&b.appointment_date===date);return `<div class="schedule-day"><div class="schedule-head"><div><strong>🧑‍⚕️ ${esc(d.name)}</strong><div class="muted">${esc(d.title||'')}</div></div><button class="btn btn-secondary" data-doctor-view="${esc(d.id)}">📅 مواعيد الطبيب</button></div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:8px;margin-top:12px">${ss.length?ss.map(slot=>slotView(d,date,slot,bs)).join(''):'<div class="empty" style="grid-column:1/-1">⚫ لا توجد ساعات عمل لهذا اليوم.</div>'}</div></div>`;}
  function slotView(d,date,slot,bs){const b=bs.find(x=>t(x.appointment_time)===slot&&x.status!=='cancelled');if(!b)return`<button class="btn btn-secondary" style="text-align:right;min-height:76px" data-book-slot="${esc(d.id)}" data-book-date="${esc(date)}" data-book-time="${esc(slot)}"><strong>🟢 ${esc(to12(slot))}</strong><div class="muted">متاح • + إضافة موعد</div></button>`;return`<div style="border:1px solid #e1e5ed;border-radius:12px;padding:10px;background:#fff"><strong>${esc(to12(slot))}</strong> ${badge(b.status)}<div style="font-weight:700;margin-top:5px">🤢 ${esc(b.patient_name||'مريض')}</div><div class="muted">${esc(b.booking_code||'')} • ${esc(b.patient_phone||'')}</div><button class="btn btn-secondary" style="margin-top:8px" data-edit-booking="${esc(b.id)}">✍️ إدارة</button></div>`;}
  function week(g){const d=new Date(`${S.date}T12:00:00`);d.setDate(d.getDate()-d.getDay());const days=Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return iso(x)});g.innerHTML=days.map(date=>`<div class="schedule-day"><h3>📅 ${esc(labelDate(date))}</h3>${S.doctors.filter(x=>!S.doctorId||String(x.id)===String(S.doctorId)).map(x=>doctorDay(x,date)).join('')}</div>`).join('');waitingRender();}
  function month(g){const [a,b]=range(),days=[];for(let d=new Date(`${a}T12:00:00`),e=new Date(`${b}T12:00:00`);d<=e;d.setDate(d.getDate()+1))days.push(iso(new Date(d)));g.innerHTML=`<div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:6px">${days.map(date=>`<button class="btn btn-secondary" style="min-height:78px;text-align:right" data-month-date="${date}"><strong>📅 ${new Date(`${date}T12:00:00`).getDate()}</strong><div class="muted">${S.bookings.filter(b=>b.appointment_date===date&&b.status!=='cancelled').length} موعد</div></button>`).join('')}</div>`;waitingRender();}
  function waitingRender(){const w=$('sv2Waiting');if(!w)return;w.innerHTML=S.waiting.length?`<div class="items">${S.waiting.map(x=>{const d=S.doctors.find(y=>String(y.id)===String(x.preferred_doctor_id||x.doctor_id));return`<div class="item"><div><strong>⏳ #${esc(x.position||'—')} • ${esc(x.patient_id)}</strong><div class="muted">${d?'🧑‍⚕️ '+esc(d.name):'🧑‍⚕️ أي طبيب'} • ${esc(x.requested_date||'بدون تاريخ')}</div><div class="muted">⭐ ${esc(x.priority||'normal')} • ${esc(x.reason||'')}</div></div><button class="btn btn-primary" data-assign-waiting="${esc(x.id)}">📅 Assign Slot</button></div>`}).join('')}</div>`:'<div class="empty">📭 لا توجد حالات انتظار نشطة.</div>';}
  async function patientSearch(v){const q=String(v||'').trim();if(!q)return[];return db('clinic_patients','id,mrn,patient_name,patient_phone,active',x=>x.eq('active',true).or(`mrn.ilike.%${q}%,patient_name.ilike.%${q}%,patient_phone.ilike.%${q}%`).limit(12));}
  function modal(html){const m=document.createElement('div');m.className='modal show';m.innerHTML=`<div class="modal-box">${html}</div>`;document.body.appendChild(m);return m;}
  function bookingModal(preset={}){const m=modal(`<h2>➕ إضافة موعد</h2><form id="sv2BookingForm"><div class="grid"><label>🔎 بحث المريض<input name="search" required></label><label>👤 المريض<select name="patient_id" required><option value="">ابحث أولًا</option></select></label><label>🧑‍⚕️ الطبيب<select name="doctor_id" required>${S.doctors.map(d=>`<option value="${esc(d.id)}" ${String(preset.doctorId||'')===String(d.id)?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label><label>🩺 الخدمة<select name="service_id" required>${S.services.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>📅 التاريخ<input name="appointment_date" type="date" value="${esc(preset.date||S.date)}" required></label><label>⏰ الوقت<input name="appointment_time" type="time" value="${esc(preset.time||'')}" required></label><label class="full">📝 ملاحظات<textarea name="notes"></textarea></label></div><div class="modal-actions"><button class="btn btn-primary">💾 حجز</button><button type="button" class="btn btn-secondary" data-close>إلغاء</button></div></form>`);const f=m.querySelector('form');f.search.oninput=async()=>{try{const r=await patientSearch(f.search.value);f.patient_id.innerHTML=r.length?r.map(p=>`<option value="${esc(p.id)}">${esc(p.mrn)} — ${esc(p.patient_name)} — ${esc(p.patient_phone||'')}</option>`).join(''):'<option value="">لا توجد نتيجة</option>'}catch(e){toast(e.message,true)}};m.querySelector('[data-close]').onclick=()=>m.remove();f.onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(f));try{await invoke('BOOK',{patient_id:p.patient_id,doctor_id:p.doctor_id,service_id:p.service_id,appointment_date:p.appointment_date,appointment_time:p.appointment_time,notes:p.notes||null});m.remove();toast('✅ تم إنشاء الموعد.');refresh()}catch(x){toast(x.message,true)}};}
  function waitingModal(){const m=modal(`<h2>⏳ إضافة إلى Waiting List</h2><form id="sv2WaitingForm"><div class="grid"><label>🔎 بحث المريض<input name="search" required></label><label>👤 المريض<select name="patient_id" required><option value="">ابحث أولًا</option></select></label><label>🧑‍⚕️ الطبيب المفضل<select name="preferred_doctor_id"><option value="">أي طبيب مناسب</option>${S.doctors.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><label>🩺 الخدمة<select name="service_id" required>${S.services.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>📅 التاريخ المطلوب<input name="requested_date" type="date" value="${esc(S.date)}"></label><label>⭐ الأولوية<select name="priority"><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></label><label class="full">📝 السبب<textarea name="reason"></textarea></label></div><div class="modal-actions"><button class="btn btn-primary">💾 إضافة</button><button type="button" class="btn btn-secondary" data-close>إلغاء</button></div></form>`);const f=m.querySelector('form');f.search.oninput=async()=>{try{const r=await patientSearch(f.search.value);f.patient_id.innerHTML=r.length?r.map(p=>`<option value="${esc(p.id)}">${esc(p.mrn)} — ${esc(p.patient_name)}</option>`).join(''):'<option value="">لا توجد نتيجة</option>'}catch(e){toast(e.message,true)}};m.querySelector('[data-close]').onclick=()=>m.remove();f.onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(f));try{await invoke('ADD_WAITING',{patient_id:p.patient_id,service_id:p.service_id,requested_date:p.requested_date||null,priority:p.priority,reason:p.reason||null,preferred_doctor_id:p.preferred_doctor_id||null});m.remove();toast('✅ تمت إضافة المريض إلى Waiting List.');refresh()}catch(x){toast(x.message,true)}};}
  async function bookingAction(id){const b=S.bookings.find(x=>String(x.id)===String(id));if(!b)return;const a=prompt('اختر: cancel / no_show / reschedule / transfer');if(!a)return;try{const x=a.toUpperCase().replace('-','_');if(x==='CANCEL'||x==='NO_SHOW')await invoke(x,{booking_id:b.id});else if(x==='RESCHEDULE'){const d=prompt('YYYY-MM-DD',b.appointment_date),tm=prompt('HH:MM',t(b.appointment_time));if(!d||!tm)return;await invoke(x,{booking_id:b.id,appointment_date:d,appointment_time:tm});}else if(x==='TRANSFER'){const d=prompt('doctor_id الجديد');if(!d)return;await invoke(x,{booking_id:b.id,doctor_id:d});}else throw Error('Action غير مدعوم.');toast('✅ تم تنفيذ الإجراء.');refresh()}catch(e){toast(e.message,true)}}
  async function assign(id){const w=S.waiting.find(x=>String(x.id)===String(id));if(!w)return;const d=prompt('YYYY-MM-DD',w.requested_date||S.date),tm=prompt('HH:MM',w.preferred_start_time?t(w.preferred_start_time):'09:00');if(!d||!tm)return;try{await invoke('ASSIGN_WAITING',{waiting_id:w.id,appointment_date:d,appointment_time:tm,doctor_id:w.preferred_doctor_id||w.doctor_id||null});toast('✅ تم تحويل الانتظار إلى موعد.');refresh()}catch(e){toast(e.message,true)}}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-book-slot]');if(b)bookingModal({doctorId:b.dataset.bookSlot,date:b.dataset.bookDate,time:b.dataset.bookTime});const eb=e.target.closest?.('[data-edit-booking]');if(eb)bookingAction(eb.dataset.editBooking);const aw=e.target.closest?.('[data-assign-waiting]');if(aw)assign(aw.dataset.assignWaiting);const md=e.target.closest?.('[data-month-date]');if(md){S.view='day';S.date=md.dataset.monthDate;$('sv2View').value='day';$('sv2Date').value=S.date;render()}const dv=e.target.closest?.('[data-doctor-view]');if(dv){S.doctorId=dv.dataset.doctorView;$('sv2Doctor').value=S.doctorId;render()}});
  window.AZAAD_SCHEDULING_V2={refresh,invoke};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',root);else root();
})();