/* AZAAD CLINIC — Scheduling V2 canonical Appwrite-Neon UI */
(()=>{
'use strict';
const API='/api/admin-appointments?resource=scheduling';const S={date:new Date().toISOString().slice(0,10),doctors:[],services:[],bookings:[],waiting:[]};const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function api(u,method='GET',body){const r=await fetch(u,{method,credentials:'include',cache:'no-store',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error||`HTTP ${r.status}`);return b}
async function action(action,body={}){return api(API,'POST',{action,...body})}
function root(){if($('azaadSchedulingV2'))return $('azaadSchedulingV2');const tabs=document.querySelector('.tabs');const tab=document.createElement('button');tab.className='tab';tab.type='button';tab.textContent='📅 Schedule V2';tabs?.appendChild(tab);const r=document.createElement('section');r.id='azaadSchedulingV2';r.className='panel';r.innerHTML=`<div class="card"><div class="panel-head"><div><h2>📅 Central Scheduling</h2><div class="muted">Appwrite session → consolidated scheduling API → Neon</div></div><button id="sv2Refresh" class="btn btn-secondary">🔄 Refresh</button></div><div class="filters"><input id="sv2Date" type="date"><select id="sv2Doctor"><option value="">All doctors</option></select></div><div id="sv2Grid"></div></div><div class="card"><h3>⏳ Waiting List</h3><div id="sv2Waiting"></div></div>`;document.querySelector('#bookings')?.parentElement?.appendChild(r);$('sv2Date').value=S.date;$('sv2Date').onchange=()=>{S.date=$('sv2Date').value||S.date;refresh()};$('sv2Refresh').onclick=refresh;tab.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');r.classList.add('active');refresh()};return r}
async function refresh(){root();try{const q=await api(`${API}&from=${encodeURIComponent(S.date)}&to=${encodeURIComponent(S.date)}`);S.doctors=q.doctors||[];S.services=q.services||[];S.bookings=q.appointments||q.bookings||[];S.waiting=q.waiting||[];const d=$('sv2Doctor');d.innerHTML='<option value="">All doctors</option>'+S.doctors.map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.full_name)}</option>`).join('');render()}catch(e){$('sv2Grid').innerHTML=`<div class="error">⚠️ ${esc(e.message)}</div>`}}
function render(){const g=$('sv2Grid');if(!g)return;g.innerHTML=S.bookings.map(b=>`<div class="list-row"><div><strong>⏰ ${esc(String(b.appointment_time||'').slice(0,5))}</strong> · ${esc(b.patient_name||b.patient?.patient_name||'Patient')}<div class="muted">🧑‍⚕️ ${esc(b.doctor_name||'')} · 🩺 ${esc(b.service_name||'')} · ${esc(b.status||'pending')}</div></div><div style="display:flex;gap:6px"><button class="btn btn-secondary" data-act="NO_SHOW" data-id="${esc(b.id)}">No-show</button><button class="btn btn-secondary" data-act="CANCEL" data-id="${esc(b.id)}">Cancel</button></div></div>`).join('')||'<div class="muted">No appointments.</div>';g.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{try{await action(b.dataset.act,{booking_id:b.dataset.id});refresh()}catch(e){alert(e.message)}});const w=$('sv2Waiting');if(w)w.innerHTML=S.waiting.map(x=>`<div class="list-row"><span>⏳ ${esc(x.position||'—')} · ${esc(x.patient_name||x.patient_id)}</span><button class="btn btn-primary" data-w="${esc(x.id)}">Assign</button></div>`).join('')||'<div class="muted">No waiting patients.</div>';w?.querySelectorAll('[data-w]').forEach(b=>b.onclick=async()=>{try{await action('ASSIGN_WAITING',{waiting_id:b.dataset.w});refresh()}catch(e){alert(e.message)}})}
async function BOOK(payload){return action('BOOK',payload)}async function RESCHEDULE(payload){return action('RESCHEDULE',payload)}async function TRANSFER(payload){return action('TRANSFER',payload)}async function CANCEL(payload){return action('CANCEL',payload)}async function NO_SHOW(payload){return action('NO_SHOW',payload)}async function ADD_WAITING(payload){return action('ADD_WAITING',payload)}async function ASSIGN_WAITING(payload){return action('ASSIGN_WAITING',payload)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,700),{once:true});else setTimeout(refresh,700);window.AZAAD_SCHEDULING_V2={refresh,BOOK,RESCHEDULE,TRANSFER,CANCEL,NO_SHOW,ADD_WAITING,ASSIGN_WAITING};
})();
