import "jsr:@supabase/functions-js@2/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL=(Deno.env.get("SUPABASE_URL")||"").trim();
function resolveKey(raw:string,prefix:string){const value=raw.trim();if(!value)return"";try{const parsed=JSON.parse(value);if(typeof parsed==="string")return parsed.trim();if(Array.isArray(parsed)){return(String(parsed.find((v)=>typeof v==="string"&&v.trim().startsWith(prefix))||parsed.find((v)=>typeof v==="string"&&v.trim())||"")).trim();}if(parsed&&typeof parsed==="object"){const values=Object.values(parsed).filter((v):v is string=>typeof v==="string"&&v.trim());return(values.find((v)=>v.trim().startsWith(prefix))||values[0]||"").trim();}}catch(_){}return value;}
function readKey(names:string[],prefix:string){for(const name of names){const key=resolveKey(Deno.env.get(name)||"",prefix);if(key)return key;}return"";}
const SECRET=readKey(["SUPABASE_SECRET_KEYS","SUPABASE_SECRET_KEY","SUPABASE_SERVICE_ROLE_KEY"],"sb_secret_");
const db=SUPABASE_URL&&SECRET?createClient(SUPABASE_URL,SECRET,{auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}}):null;
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,apikey,authorization","Access-Control-Allow-Methods":"GET,OPTIONS","Cache-Control":"public,max-age=60,s-maxage=60,stale-while-revalidate=300","Content-Type":"application/json; charset=utf-8"};
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='GET')return new Response(JSON.stringify({error:'GET required'}),{status:405,headers:C});if(!db)return new Response(JSON.stringify({error:'team_unavailable',code:'TEAM_DB_CONFIGURATION'}),{status:503,headers:C});try{const[d,t]=await Promise.all([db.from('clinic_doctors').select('id,name,name_en,title,title_en,bio,bio_en,image_url,sort_order,active').eq('active',true).order('sort_order'),db.from('clinic_public_team_profiles').select('id,staff_id,display_name,display_name_en,title,title_en,department,department_en,image_url,bio,bio_en,sort_order,active').eq('active',true).eq('show_on_patient_portal',true).order('sort_order')]);if(d.error||t.error)throw d.error||t.error;return new Response(JSON.stringify({doctors:d.data||[],team:t.data||[]}),{headers:C});}catch(e){console.error('public team data failure',e instanceof Error?e.message:String(e));return new Response(JSON.stringify({error:'team_unavailable'}),{status:503,headers:C});}});
