import "jsr:@supabase/functions-js@2/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")??"";
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ANON=Deno.env.get("SUPABASE_ANON_KEY")??"";
const db=createClient(URL,SERVICE,{auth:{autoRefreshToken:false,persistSession:false}});
const ORIGINS=new Set(["https://magdy4287-beep.github.io","https://azaad-clinic-website.vercel.app","https://azaad-clinic-website-magdy-team.vercel.app","http://localhost:3000","http://localhost:5173","http://127.0.0.1:3000","http://127.0.0.1:5173"]);
function json(body:unknown,status=200,req?:Request){const origin=req?.headers.get("Origin")||"";return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":ORIGINS.has(origin)?origin:"https://magdy4287-beep.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Vary":"Origin"}})}
function clean(v:unknown){return String(v??"").trim()}
async function doctorContext(req:Request){const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("Unauthorized");const client=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{autoRefreshToken:false,persistSession:false}});const u=await client.auth.getUser();if(u.error||!u.data?.user)throw new Error("Unauthorized");const q=await db.from("clinic_staff").select("id,auth_user_id,full_name,username,email,role,active,doctor_id").eq("auth_user_id",u.data.user.id).maybeSingle();if(q.error)throw new Error("تعذر التحقق من حساب الطبيب.");const staff=q.data;if(!staff||staff.active!==true||String(staff.role).toUpperCase()!=="DOCTOR"||!staff.doctor_id)throw new Error("هذا الحساب ليس حساب طبيب مرتبطًا.");const d=await db.from("clinic_doctors").select("id,name,name_en,title,title_en,bio,bio_en,image_url,active").eq("id",staff.doctor_id).eq("active",true).maybeSingle();if(d.error||!d.data)throw new Error("سجل الطبيب غير موجود أو غير نشط.");return{staff,doctor:d.data}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return json({ok:true},200,req);if(req.method!=="GET"&&req.method!=="POST")return json({error:"GET or POST required"},405,req);try{const{staff,doctor}=await doctorContext(req);let body:any={};if(req.method==="POST"){try{body=await req.json()}catch{body={}}}const u=new URL(req.url),date=clean(body.date)||clean(u.searchParams.get("date")),from=clean(body.from)||clean(u.searchParams.get("from")),to=clean(body.to)||clean(u.searchParams.get("to")),limit=Math.min(Math.max(Number(body.limit)||100,1),200);let bq=db.from("clinic_bookings").select("id,booking_code,doctor_id,service_id,patient_id,patient_name,patient_phone,patient_email,appointment_date,appointment_time,mode,notes,status,created_at,updated_at,payment_status,service_authorization_status").eq("doctor_id",doctor.id).order("appointment_date",{ascending:true}).order("appointment_time",{ascending:true}).limit(limit);if(date)bq=bq.eq("appointment_date",date);else{if(from)bq=bq.gte("appointment_date",from);if(to)bq=bq.lte("appointment_date",to)}const b=await bq;if(b.error)throw new Error("تعذر تحميل جدول الطبيب.");const w=await db.from("clinic_waiting_list").select("id,patient_id,doctor_id,preferred_doctor_id,service_id,requested_date,preferred_start_time,preferred_end_time,priority,reason,patient_phone_snapshot,status,position,source,notes,created_at,updated_at,contacted_at,confirmed_at,expires_at,converted_booking_id").or(`doctor_id.eq.${doctor.id},preferred_doctor_id.eq.${doctor.id}`).in("status",["WAITING","PENDING","ACTIVE"]).order("position",{ascending:true}).limit(200);if(w.error)throw new Error("تعذر تحميل قائمة الانتظار.");const ids=[...(b.data||[]).map(x=>x.patient_id),...(w.data||[]).map(x=>x.patient_id)].filter(Boolean),unique=[...new Set(ids)];let patients:any[]=[];if(unique.length){const p=await db.from("clinic_patients").select("id,mrn,patient_name,patient_phone,patient_email,date_of_birth,gender,active,created_at,updated_at").in("id",unique);if(p.error)throw new Error("تعذر تحميل بيانات المرضى.");patients=p.data||[]}const pm=new Map(patients.map(p=>[String(p.id),p]));return json({ok:true,doctor,staff:{id:staff.id,full_name:staff.full_name,username:staff.username,email:staff.email},scope:{doctor_id:doctor.id},appointments:(b.data||[]).map(x=>({...x,patient:x.patient_id?pm.get(String(x.patient_id))||null:null})),waiting_list:(w.data||[]).map(x=>({...x,patient:x.patient_id?pm.get(String(x.patient_id))||null:null})),patients},200,req)}catch(e){const message=e instanceof Error?e.message:"Internal server error";return json({error:message},message==="Unauthorized"?401:403,req)}});
