#!/usr/bin/env bash
set -euo pipefail

clean_env() { printf '%s' "${1:-}" | tr -d '\r\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }
SUPABASE_URL="$(clean_env "${SUPABASE_URL:-}")"; SUPABASE_SERVICE_ROLE_KEY="$(clean_env "${SUPABASE_SERVICE_ROLE_KEY:-}")"; APPWRITE_ENDPOINT="$(clean_env "${APPWRITE_ENDPOINT:-}")"; APPWRITE_PROJECT_ID="$(clean_env "${APPWRITE_PROJECT_ID:-}")"; APPWRITE_API_KEY="$(clean_env "${APPWRITE_API_KEY:-}")"
: "${SUPABASE_URL:?Missing SUPABASE_URL}"; : "${SUPABASE_SERVICE_ROLE_KEY:?Missing SUPABASE_SERVICE_ROLE_KEY}"; : "${APPWRITE_ENDPOINT:?Missing APPWRITE_ENDPOINT}"; : "${APPWRITE_PROJECT_ID:?Missing APPWRITE_PROJECT_ID}"; : "${APPWRITE_API_KEY:?Missing APPWRITE_API_KEY}"
SUPABASE_URL="${SUPABASE_URL%/}"; [[ "$SUPABASE_URL" =~ ^https://app\.supabase\.com/dashboard/project/([a-z0-9]+)(/.*)?$ ]] && SUPABASE_URL="https://${BASH_REMATCH[1]}.supabase.co" || true
[[ "$SUPABASE_URL" =~ ^https://([a-z0-9]+)\.supabase\.co(/rest/v1|/storage/v1|/auth/v1)?$ ]] && SUPABASE_URL="https://${BASH_REMATCH[1]}.supabase.co" || true
APPWRITE_ENDPOINT="${APPWRITE_ENDPOINT%/}"
export SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY APPWRITE_ENDPOINT APPWRITE_PROJECT_ID APPWRITE_API_KEY

node <<'NODE'
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const supabase=process.env.SUPABASE_URL,supaKey=process.env.SUPABASE_SERVICE_ROLE_KEY,aw=process.env.APPWRITE_ENDPOINT,project=process.env.APPWRITE_PROJECT_ID,awKey=process.env.APPWRITE_API_KEY;
const out=path.join(process.env.RUNNER_TEMP||'/tmp','azaad-storage-migration'),CHUNK=5*1024*1024,APPWRITE_MAX_FILE_SIZE=50_000_000;
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true,mode:0o700});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function request(url,opt={},label='request'){for(let a=1;a<=4;a++){try{const r=await fetch(url,opt);if(r.ok)return r;if((r.status===429||r.status>=500)&&a<4){await sleep(1000*a);continue;}let d='';try{d=(await r.text()).slice(0,500)}catch{}throw Error(`${label}: HTTP ${r.status}${d?' — '+d:''}`)}catch(e){if(a===4)throw e;if(!String(e.message).includes('HTTP 4'))await sleep(1000*a);else throw e}}}
async function json(url,opt,label){return (await request(url,opt,label)).json()}
const sh=()=>({apikey:supaKey,Accept:'application/json',...(supaKey.startsWith('sb_secret_')?{}:{Authorization:`Bearer ${supaKey}`})});
const ah=()=>({'X-Appwrite-Project':project,'X-Appwrite-Key':awKey,Accept:'application/json'});
const fid=(b,p)=>crypto.createHash('sha256').update(`${b}\0${p}`).digest('hex').slice(0,36);
const bid=n=>`${(n.toLowerCase().replace(/[^a-z0-9._-]/g,'-').replace(/^-+|-+$/g,'').slice(0,24)||'bucket')}-${crypto.createHash('sha256').update(n).digest('hex').slice(0,10)}`.slice(0,36);
const fname=p=>{const b=path.posix.basename(p)||'file',s='-'+crypto.createHash('sha256').update(p).digest('hex').slice(0,10);return (b.length+s.length<=255?b:b.slice(0,255-s.length))+s};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function listBucket(b,p=''){let rows=[];for(let o=0;;o+=1000){const d=await json(`${supabase}/storage/v1/object/list/${encodeURIComponent(b)}`,{method:'POST',headers:{...sh(),'Content-Type':'application/json'},body:JSON.stringify({prefix:p,limit:1000,offset:o,sortBy:{column:'name',order:'asc'}})},`Supabase list ${b}/${p}`);if(!Array.isArray(d)||!d.length)break;rows.push(...d);if(d.length<1000)break}return rows}
async function walk(b,p=''){const es=await listBucket(b,p),fs=[];for(const e of es){if(!e?.name)continue;const f=p?`${p.replace(/\/$/,'')}/${e.name}`:e.name;if(e.id)fs.push({path:f,metadata:e.metadata||null});else fs.push(...await walk(b,f))}return fs}
async function buckets(){let r=[];for(let o=0;;o+=100){const d=await json(`${aw}/storage/buckets?limit=100&offset=${o}`,{headers:ah()},'Appwrite bucket list'),x=d.buckets||[];r.push(...x);if(x.length<100)break}return r}
async function ensure(id,name){const d={bucketId:id,name,permissions:[],fileSecurity:false,enabled:true,maximumFileSize:APPWRITE_MAX_FILE_SIZE,allowedFileExtensions:[],compression:'none',encryption:false,antivirus:false,transformations:false};return json(`${aw}/storage/buckets`,{method:'POST',headers:{...ah(),'Content-Type':'application/json'},body:JSON.stringify(d)},`Appwrite create bucket ${name}`)}
async function get(url,label){const r=await fetch(url,{headers:ah()});if(r.status===404)return null;if(!r.ok)throw Error(`${label}: HTTP ${r.status}`);return r.json()}
async function upload(b,f,bytes,mime){const id=fid(f.sourceBucket,f.path),name=fname(f.path),total=bytes.length;if(total>APPWRITE_MAX_FILE_SIZE)throw Error(`FAIL-CLOSED: ${f.sourceBucket}/${f.path} is ${total} bytes, above Appwrite Cloud maximum ${APPWRITE_MAX_FILE_SIZE}; refusing lossy split`);for(let s=0;s<total;s+=CHUNK){const e=Math.min(s+CHUNK,total)-1,part=bytes.subarray(s,e+1),form=new FormData();if(s===0)form.append('fileId',id);form.append('file',new Blob([part],{type:mime}),name);form.append('permissions[]','read("any")');const h={...ah(),'Content-Range':`bytes ${s}-${e}/${total}`};if(s>0)h['X-Appwrite-ID']=id;await request(`${aw}/storage/buckets/${encodeURIComponent(b)}/files`,{method:'POST',headers:h,body:form},`Appwrite upload ${f.sourceBucket}/${f.path} ${s}-${e}`)}}
(async()=>{const manifest={candidate_sha:process.env.GITHUB_SHA||'unknown',started_at:new Date().toISOString(),buckets:[],source_deleted:false,status:'RUNNING'};const sr=await request(`${supabase}/storage/v1/bucket`,{headers:sh()},'Supabase bucket inventory'),sb=await sr.json();if(!Array.isArray(sb))throw Error('Supabase bucket inventory was not an array');const ab=await buckets();for(const b of sb){const target=ab.find(x=>x.name===b.name)||await ensure(b.id?.length<=36?b.id:bid(b.name),b.name),files=await walk(b.id),rec={source_bucket:b.id,source_name:b.name,destination_bucket:target.$id,destination_name:target.name,file_count:files.length,uploaded:0,verified:0,failed:[]};manifest.buckets.push(rec);for(const f0 of files){const f={...f0,sourceBucket:b.id};try{const url=`${supabase}/storage/v1/object/authenticated/${encodeURIComponent(b.id)}/${f.path.split('/').map(encodeURIComponent).join('/')}`,r=await request(url,{headers:sh()},`Supabase download ${b.id}/${f.path}`),bytes=Buffer.from(await r.arrayBuffer()),expected=sha(bytes),size=bytes.length,id=fid(b.id,f.path),existing=await get(`${aw}/storage/buckets/${encodeURIComponent(target.$id)}/files/${encodeURIComponent(id)}`,`Appwrite existence ${f.path}`);if(existing){if(Number(existing.sizeOriginal)!==size)throw Error(`destination size mismatch for ${f.path}`)}else{await upload(target.$id,f,bytes,f.metadata?.mimetype||'application/octet-stream');rec.uploaded++}const verify=await get(`${aw}/storage/buckets/${encodeURIComponent(target.$id)}/files/${encodeURIComponent(id)}`,`Appwrite verify ${f.path}`);if(!verify||Number(verify.sizeOriginal)!==size)throw Error(`reconciliation failed for ${f.path}: size`);const content=Buffer.from(await (await request(`${aw}/storage/buckets/${encodeURIComponent(target.$id)}/files/${encodeURIComponent(id)}/download`,{headers:ah()},`Appwrite download ${f.path}`)).arrayBuffer());if(sha(content)!==expected)throw Error(`reconciliation failed for ${f.path}: checksum`);rec.verified++}catch(e){rec.failed.push({path:f.path,error:e.message});throw e}}}manifest.finished_at=new Date().toISOString();manifest.status='PASS';fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2),{mode:0o600});console.log(`PASS: verified ${manifest.buckets.reduce((n,b)=>n+b.verified,0)} storage objects across ${manifest.buckets.length} buckets`);console.log('PASS: source Supabase storage was not deleted')})().catch(e=>{console.error(`FAIL-CLOSED: storage migration stopped: ${e.message}`);process.exit(1)})
NODE