const SUPABASE_URL=(Deno.env.get("SUPABASE_URL")||"").trim();
function resolveKey(raw:string,prefix:string){const value=raw.trim();if(!value)return"";try{const parsed=JSON.parse(value);if(typeof parsed==='string')return parsed.trim();if(Array.isArray(parsed)){const preferred=parsed.find(v=>typeof v==='string'&&v.trim().startsWith(prefix));return(String(preferred||parsed.find(v=>typeof v==='string'&&v.trim())||'')).trim();}if(parsed&&typeof parsed==='object'){const values=Object.values(parsed).filter((v):v is string=>typeof v==='string'&&v.trim());const preferred=values.find(v=>v.trim().startsWith(prefix));if(preferred)return preferred.trim();for(const key of ['default','current','value']){const candidate=parsed[key];if(typeof candidate==='string'&&candidate.trim())return candidate.trim();}return(values[0]||'').trim();}}catch(_){}return value;}
function readKey(names:string[],prefix:string){for(const name of names){const key=resolveKey(Deno.env.get(name)||'',prefix);if(key)return key;}return'';}
const LEGACY_SERVICE_ROLE=(Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'').trim();
const SECRET_KEY=LEGACY_SERVICE_ROLE||readKey(['SUPABASE_SECRET_KEYS','SUPABASE_SECRET_KEY'],'sb_secret_');
const PUBLISHABLE_KEY=readKey(['SUPABASE_PUBLISHABLE_KEYS','SUPABASE_PUBLISHABLE_KEY','SUPABASE_ANON_KEY'],'sb_publishable_');
function dbHeaders(){const h:Record<string,string>={apikey:SECRET_KEY,Accept:'application/json'};if(!SECRET_KEY.startsWith('sb_secret_'))h.Authorization=`Bearer ${SECRET_KEY}`;return h;}
const ORIGINS=new Set(['https://magdy4287-beep.github.io','https://azaad-clinic-website.vercel.app','https://azaad-clinic-website-magdy-team.vercel.app','https://azaad-clinic-website-git-main-magdy-team.vercel.app','http://localhost:3000','http://localhost:5173','http://localhost:4173','http://127.0.0.1:3000','http://127.0.0.1:4173']);
function cors(req:Request){const origin=req.headers.get('Origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(origin)?origin:'https://azaad-clinic-website.vercel.app','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, accept','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Credentials':'true','Cache-Control':'no-store',Vary:'Origin'};}
function json(body:unknown,status=200,req?:Request){return new Response(JSON.stringify(body),{status,headers:{...(req?cors(req):{}),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});}
async function findStaff(username:string){if(!SUPABASE_URL||!SECRET_KEY)throw new Error('STAFF_DB_CONFIGURATION_MISSING');const url=new URL(`${SUPABASE_URL}/rest/v1/clinic_staff`);url.searchParams.set('select','id,auth_user_id,full_name,username,email,phone,role,active');url.searchParams.set('username',`eq.${username}`);url.searchParams.set('limit','1');const r=await fetch(url,{headers:dbHeaders()});const text=await r.text();if(!r.ok){console.error('clinic_staff lookup failed',{status:r.status,body:text.slice(0,300),usingLegacy:Boolean(LEGACY_SERVICE_ROLE),usingSecret:SECRET_KEY.startsWith('sb_secret_')});throw new Error(`STAFF_LOOKUP_HTTP_${r.status}`);}const rows=JSON.parse(text);return Array.isArray(rows)?rows[0]||null:null;}
async function passwordSignIn(email:string,password:string){if(!SUPABASE_URL||!PUBLISHABLE_KEY)throw new Error('AUTH_CONFIGURATION_MISSING');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({email,password}),signal:controller.signal});const text=await r.text();let payload:Record<string,unknown>={};try{payload=JSON.parse(text);}catch(_){}if(!r.ok){console.error('auth password endpoint failed',{status:r.status,error:typeof payload.error==='string'?payload.error:'unknown',errorCode:typeof payload.error_code==='string'?payload.error_code:'unknown'});return{ok:false,payload};}if(!payload.access_token||!payload.refresh_token||!payload.user)return{ok:false,payload:{error:'AUTH_SESSION_MISSING'}};return{ok:true,payload};}finally{clearTimeout(timer);}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json({error:'Method not allowed'},405,req);try{if(!SUPABASE_URL||!SECRET_KEY||!PUBLISHABLE_KEY){console.error('staff-login configuration incomplete',{hasUrl:Boolean(SUPABASE_URL),hasSecretKey:Boolean(SECRET_KEY),hasPublishableKey:Boolean(PUBLISHABLE_KEY),usingLegacy:Boolean(LEGACY_SERVICE_ROLE),usingSecret:SECRET_KEY.startsWith('sb_secret_')});return json({error:'تسجيل الدخول غير متاح حاليًا.',code:'STAFF_LOGIN_CONFIGURATION'},503,req);}const body=await req.json();const username=String(body?.username||'').trim().toLowerCase();const password=String(body?.password||'');if(!username||!password)return json({error:'اسم المستخدم وكلمة المرور مطلوبان.'},400,req);const staffProfile=await findStaff(username);if(!staffProfile)return json({error:'بيانات الدخول غير صحيحة أو الحساب غير موجود.'},401,req);if(!staffProfile.active)return json({error:'الحساب غير فعال.'},403,req);if(!staffProfile.email||!staffProfile.auth_user_id)return json({error:'حساب الموظف غير مكتمل.'},403,req);const auth=await passwordSignIn(staffProfile.email,password);if(!auth.ok)return json({error:'بيانات الدخول غير صحيحة.',code:'AUTH_SIGNIN_FAILED'},401,req);return json({success:true,user:auth.payload.user,session:{access_token:auth.payload.access_token,refresh_token:auth.payload.refresh_token,expires_in:auth.payload.expires_in,expires_at:auth.payload.expires_at,token_type:auth.payload.token_type},staff:staffProfile},200,req);}catch(error){console.error('staff-login failure',error instanceof Error?error.message:String(error));return json({error:'تعذر تجهيز تسجيل الدخول. حاول مرة أخرى.',code:'STAFF_LOGIN_FAILED'},500,req);}});
