const SUPABASE_URL=(Deno.env.get('SUPABASE_URL')||'').trim();
function resolveKey(raw:string,prefix:string){const value=raw.trim();if(!value)return '';try{const parsed=JSON.parse(value);if(typeof parsed==='string')return parsed.trim();if(Array.isArray(parsed)){const preferred=parsed.find(v=>typeof v==='string'&&v.trim().startsWith(prefix));return String(preferred||parsed.find(v=>typeof v==='string'&&v.trim())||'').trim();}if(parsed&&typeof parsed==='object'){const values=Object.values(parsed).filter((v):v is string=>typeof v==='string'&&v.trim());const preferred=values.find(v=>v.trim().startsWith(prefix));if(preferred)return preferred.trim();for(const key of ['default','current','value']){const candidate=parsed[key];if(typeof candidate==='string'&&candidate.trim())return candidate.trim();}return (values[0]||'').trim();}}catch(_){}return value;}
function readKey(names:string[],prefix:string){for(const name of names){const key=resolveKey(Deno.env.get(name)||'',prefix);if(key)return key;}return '';}
const LEGACY_SERVICE_ROLE=(Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'').trim();
const SECRET_KEY=LEGACY_SERVICE_ROLE||readKey(['SUPABASE_SECRET_KEYS','SUPABASE_SECRET_KEY'],'sb_secret_');
const PUBLISHABLE_KEY=readKey(['SUPABASE_PUBLISHABLE_KEYS','SUPABASE_PUBLISHABLE_KEY','SUPABASE_ANON_KEY'],'sb_publishable_');
const ORIGINS=new Set(['https://magdy4287-beep.github.io','https://azaad-clinic-website.vercel.app','https://azaad-clinic-website-magdy-team.vercel.app','https://azaad-clinic-website-git-main-magdy-team.vercel.app','http://localhost:3000','http://localhost:5173','http://localhost:4173','http://127.0.0.1:3000','http://127.0.0.1:4173']);
function cors(req:Request){const origin=req.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':ORIGINS.has(origin)?origin:'https://azaad-clinic-website.vercel.app','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, accept','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Credentials':'true','Cache-Control':'no-store',Vary:'Origin'};}
function json(body:unknown,status=200,req?:Request){return new Response(JSON.stringify(body),{status,headers:{...(req?cors(req):{}),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});}
function dbHeaders(){const h:Record<string,string>={apikey:SECRET_KEY,Accept:'application/json'};if(SECRET_KEY&&!SECRET_KEY.startsWith('sb_secret_'))h.Authorization=`Bearer ${SECRET_KEY}`;return h;}
async function findStaff(username:string){if(!SUPABASE_URL||!SECRET_KEY)throw new Error('STAFF_DB_CONFIGURATION_MISSING');const url=new URL(`${SUPABASE_URL}/rest/v1/clinic_staff`);url.searchParams.set('select','id,auth_user_id,full_name,username,email,phone,role,active');url.searchParams.set('username',`eq.${username}`);url.searchParams.set('limit','1');const r=await fetch(url,{headers:dbHeaders()});const text=await r.text();if(!r.ok){console.error('clinic_staff lookup failed',{status:r.status,body:text.slice(0,300)});throw new Error(`STAFF_LOOKUP_HTTP_${r.status}`);}let rows:unknown;try{rows=JSON.parse(text);}catch(_){throw new Error('STAFF_LOOKUP_INVALID_JSON');}return Array.isArray(rows)?rows[0]||null:null;}
async function passwordSignIn(email:string,password:string){if(!SUPABASE_URL||!PUBLISHABLE_KEY)throw new Error('AUTH_CONFIGURATION_MISSING');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({email,password}),signal:controller.signal});const text=await r.text();let payload:Record<string,unknown>;try{payload=JSON.parse(text);}catch(_){console.error('auth password endpoint returned non-json',{status:r.status,contentType:r.headers.get('content-type')});return {ok:false,kind:'UPSTREAM_INVALID_JSON'};}if(!r.ok){console.error('auth password endpoint failed',{status:r.status,error:typeof payload.error==='string'?payload.error:'unknown',errorCode:typeof payload.error_code==='string'?payload.error_code:'unknown'});return {ok:false,kind:'AUTH_REJECTED'};}if(typeof payload.access_token!=='string'||typeof payload.refresh_token!=='string'||!payload.user)return {ok:false,kind:'AUTH_SESSION_MISSING'};return {ok:true,payload};}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return {ok:false,kind:'AUTH_TIMEOUT'};throw error;}finally{clearTimeout(timer);}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json({error:'Method not allowed'},405,req);try{if(!SUPABASE_URL||!SECRET_KEY||!PUBLISHABLE_KEY)return json({error:'تسجيل الدخول غير متاح حاليًا.',code:'STAFF_LOGIN_CONFIGURATION'},503,req);let body:Record<string,unknown>;try{body=await req.json();}catch(_){return json({error:'طلب تسجيل الدخول غير صالح.',code:'INVALID_JSON'},400,req);}const username=String(body.username||'').trim().toLowerCase();const password=String(body.password||'');if(!username||!password)return json({error:'اسم المستخدم وكلمة المرور مطلوبان.'},400,req);const staffProfile=await findStaff(username) as Record<string,unknown>|null;if(!staffProfile)return json({error:'بيانات الدخول غير صحيحة أو الحساب غير موجود.'},401,req);if(staffProfile.active!==true)return json({error:'الحساب غير فعال.'},403,req);const email=typeof staffProfile.email==='string'?staffProfile.email.trim():'';const authUserId=typeof staffProfile.auth_user_id==='string'?staffProfile.auth_user_id.trim():'';if(!email||!authUserId)return json({error:'حساب الموظف غير مكتمل.'},403,req);const auth=await passwordSignIn(email,password);if(!auth.ok)return json({error:'بيانات الدخول غير صحيحة.',code:'AUTH_SIGNIN_FAILED'},401,req);const p=auth.payload as Record<string,unknown>;return json({success:true,user:p.user,session:{access_token:p.access_token,refresh_token:p.refresh_token,expires_in:p.expires_in,expires_at:p.expires_at,token_type:p.token_type},staff:staffProfile},200,req);}catch(error){console.error('staff-login failure',error instanceof Error?error.message:String(error));return json({error:'تعذر تجهيز تسجيل الدخول. حاول مرة أخرى.',code:'STAFF_LOGIN_FAILED'},500,req);}});
