CREATE OR REPLACE FUNCTION public.clinic_public_book_appointment_action(p_patient_name text,p_patient_phone text,p_patient_email text,p_doctor_id uuid,p_service_id uuid,p_appointment_date date,p_appointment_time time without time zone,p_mode text DEFAULT 'clinic'::text,p_notes text DEFAULT NULL::text,p_patient_language text DEFAULT NULL::text)
RETURNS public.clinic_bookings LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_catalog AS $$
declare v_patient public.clinic_patients; v_booking public.clinic_bookings; v_doctor public.clinic_doctors; v_service public.clinic_services; v_schedule record; v_override record; v_holiday record; v_phone text; v_mode text; v_start integer; v_end integer; v_time integer; v_break_start integer; v_break_end integer; v_duration integer; v_buffer integer; v_max_daily integer; v_daily_count integer; v_code text; v_conflict boolean;
begin
 if nullif(btrim(p_patient_name),'') is null then raise exception 'patient_name_required'; end if;
 if nullif(btrim(p_patient_phone),'') is null then raise exception 'patient_phone_required'; end if;
 if p_doctor_id is null or p_service_id is null or p_appointment_date is null or p_appointment_time is null then raise exception 'booking_fields_required'; end if;
 v_mode:=case when lower(coalesce(p_mode,'clinic')) in ('online','online_session','online-session') then 'online' else 'clinic' end;
 v_phone:=public.clinic_normalize_phone(p_patient_phone); if v_phone is null or length(v_phone)<8 or length(v_phone)>15 then raise exception 'invalid_phone'; end if;
 if p_patient_email is not null and btrim(p_patient_email)<>'' and p_patient_email !~* '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$' then raise exception 'invalid_email'; end if;
 select * into v_doctor from public.clinic_doctors where id=p_doctor_id and active=true; if not found then raise exception 'doctor_not_available'; end if;
 select * into v_service from public.clinic_services where id=p_service_id and active=true; if not found then raise exception 'service_not_available'; end if;
 if array_length(v_doctor.services,1) is not null and not (p_service_id::text=any(v_doctor.services::text[])) then raise exception 'service_not_assigned_to_doctor'; end if;
 select * into v_override from public.doctor_schedule_overrides where doctor_id=p_doctor_id and override_date=p_appointment_date limit 1; if found and lower(coalesce(v_override.type,'')) in ('closed','off','unavailable','holiday') then raise exception 'doctor_unavailable'; end if;
 select * into v_holiday from public.clinic_holidays where p_appointment_date between start_date and end_date and closed=true and (applies_to='all' or applies_to='clinic' or (applies_to='doctor' and doctor_id=p_doctor_id)) limit 1; if found then raise exception 'clinic_closed'; end if;
 select * into v_schedule from public.doctor_weekly_schedules where doctor_id=p_doctor_id and weekday=extract(dow from p_appointment_date)::integer and enabled=true and (mode=v_mode or mode='both' or (v_mode='clinic' and mode='in_clinic')) order by case when mode=v_mode then 0 when mode='both' then 1 else 2 end limit 1; if not found then raise exception 'doctor_not_scheduled'; end if;
 if v_override.id is not null then if v_override.start_time is not null then v_schedule.start_time:=v_override.start_time; end if; if v_override.end_time is not null then v_schedule.end_time:=v_override.end_time; end if; if v_override.break_start is not null then v_schedule.break_start:=v_override.break_start; end if; if v_override.break_end is not null then v_schedule.break_end:=v_override.break_end; end if; if v_override.buffer_minutes is not null then v_schedule.buffer_minutes:=v_override.buffer_minutes; end if; if v_override.max_daily_bookings is not null then v_schedule.max_daily_bookings:=v_override.max_daily_bookings; end if; end if;
 v_duration:=greatest(coalesce(v_service.duration_minutes,30),1); v_buffer:=greatest(coalesce(v_schedule.buffer_minutes,0),0); v_start:=extract(hour from v_schedule.start_time)::integer*60+extract(minute from v_schedule.start_time)::integer; v_end:=extract(hour from v_schedule.end_time)::integer*60+extract(minute from v_schedule.end_time)::integer; v_time:=extract(hour from p_appointment_time)::integer*60+extract(minute from p_appointment_time)::integer; v_break_start:=case when v_schedule.break_start is null then null else extract(hour from v_schedule.break_start)::integer*60+extract(minute from v_schedule.break_start)::integer end; v_break_end:=case when v_schedule.break_end is null then null else extract(hour from v_schedule.break_end)::integer*60+extract(minute from v_schedule.break_end)::integer end; v_max_daily:=case when v_schedule.max_daily_bookings is null then null else greatest(v_schedule.max_daily_bookings,0) end;
 if p_appointment_date<(now() at time zone 'Africa/Cairo')::date then raise exception 'appointment_in_past'; end if; if p_appointment_date=(now() at time zone 'Africa/Cairo')::date and v_time<=extract(hour from(now() at time zone 'Africa/Cairo'))::integer*60+extract(minute from(now() at time zone 'Africa/Cairo'))::integer then raise exception 'appointment_in_past'; end if; if v_time<v_start or v_time+v_duration>v_end then raise exception 'outside_working_hours'; end if; if v_break_start is not null and v_break_end is not null and v_time<v_break_end and v_time+v_duration>v_break_start then raise exception 'break_conflict'; end if;
 perform pg_advisory_xact_lock(hashtext(v_phone)); perform pg_advisory_xact_lock(hashtext(p_doctor_id::text||':'||p_appointment_date::text));
 if v_max_daily is not null then select count(*) into v_daily_count from public.clinic_bookings where doctor_id=p_doctor_id and appointment_date=p_appointment_date and status in ('pending','confirmed'); if v_daily_count>=v_max_daily then raise exception 'daily_booking_limit_reached'; end if; end if;
 select exists(select 1 from public.clinic_bookings b join public.clinic_services s on s.id=b.service_id where b.doctor_id=p_doctor_id and b.appointment_date=p_appointment_date and b.mode=v_mode and b.status in ('pending','confirmed') and v_time<(extract(hour from b.appointment_time)::integer*60+extract(minute from b.appointment_time)::integer+greatest(coalesce(s.duration_minutes,30),1)+v_buffer) and v_time+v_duration+v_buffer>(extract(hour from b.appointment_time)::integer*60+extract(minute from b.appointment_time)::integer)) into v_conflict; if v_conflict then raise exception 'appointment_conflict'; end if;
 select * into v_patient from public.clinic_patients where patient_phone_normalized=v_phone and active=true order by created_at asc limit 1;
 if not found then insert into public.clinic_patients(mrn,patient_name,patient_phone,patient_phone_normalized,patient_email,active) values(public.next_patient_mrn(),left(btrim(p_patient_name),200),left(btrim(p_patient_phone),50),v_phone,nullif(btrim(p_patient_email),''),true) returning * into v_patient; end if;
 v_code:='AZD-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
 insert into public.clinic_bookings(booking_code,doctor_id,service_id,patient_id,patient_name,patient_phone,patient_email,appointment_date,appointment_time,mode,notes,status,payment_status,service_authorization_status) values(v_code,p_doctor_id,p_service_id,v_patient.id,v_patient.patient_name,v_patient.patient_phone,v_patient.patient_email,p_appointment_date,p_appointment_time,v_mode,nullif(left(btrim(coalesce(p_notes,'')),2000),''),'pending','unpaid','pending') returning * into v_booking; return v_booking;
end;$$;
REVOKE ALL ON FUNCTION public.clinic_public_book_appointment_action(text,text,text,uuid,uuid,date,time,text,text,text) FROM public;
GRANT EXECUTE ON FUNCTION public.clinic_public_book_appointment_action(text,text,text,uuid,uuid,date,time,text,text,text) TO anon,authenticated;
