import { neon } from '@neondatabase/serverless';

const COOKIE='azaad_admin_appwrite_session';
const OWNER_ROLES=new Set(['OWNER','ADMIN']);
function out(res,b,s=200){res.statusCode=s;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(b));}
function getCookie(req){const m=String(req.headers.cookie||'').match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]*)`));return m?decodeURIComponent(m[1]):'';}
async function appwriteUser(secret){const endpoint=String(process.env.APPWRITE_ENDPOINT||'').replace(/\/$/,'');const project=String(process.env.APPWRITE_PROJECT_ID||'').trim();if(!endpoint||!project||!secret)return null;const r=await fetch(`${endpoint}/account`,{headers:{'X-Appwrite-Project':project,Cookie:`a_session_${project}=${secret}; a_session_${project}_legacy=${secret}`}});return r.ok?r.json():null;}
async function identity(req){const user=await appwriteUser(getCookie(req));if(!user?.$id)return null;const databaseUrl=String(process.env.DATABASE_URL||'').trim();if(!databaseUrl)throw new Error('DATABASE_RUNTIME_NOT_CONFIGURED');const sql=neon(databaseUrl);const rows=await sql`select id,role,active,account_status from public.clinic_staff where auth_user_id=${user.$id} and active=true limit 1`;const staff=rows[0];if(!staff||staff.account_status!=='active')return null;return{sql,staff,role:String(staff.role||'').toUpperCase()};}
async function readBody(req){if(req.body&&typeof req.body==='object')return req.body;return new Promise(resolve=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch{resolve({});}});req.on('error',()=>resolve({}));});}
async function dependenciesSatisfied(sql,moduleKey){const rows=await sql`select dependencies from public.facility_module_registry where module_key=${moduleKey} and certification_status='CERTIFIED' and enabled=true limit 1`;if(!rows[0])return false;const deps=Array.isArray(rows[0].dependencies)?rows[0].dependencies:[];if(!deps.length)return true;const states=await sql`select module_key,enabled,certification_status from public.facility_module_registry where module_key = any(${deps})`;return deps.every(d=>states.some(x=>x.module_key===d&&x.enabled&&x.certification_status==='CERTIFIED'));}
export default async function handler(req,res){try{const x=await identity(req);if(!x)return out(res,{error:'unauthorized'},401);const{sql,staff,role}=x;const url=new URL(req.url||'/','https://azaad.invalid');if(req.method==='GET'){const[mode,modules]=await Promise.all([sql`select * from public.facility_operating_mode where active=true limit 1`,sql`select module_key,module_group,display_name_key,enabled,clinic_available,hospital_available,dependencies,certification_status,version from public.facility_module_registry order by module_group,module_key`]);return out(res,{mode:mode[0]||null,modules,provider:'appwrite-neon'});}if(req.method!=='POST'||!OWNER_ROLES.has(role))return out(res,{error:'forbidden'},403);const b=await readBody(req);if(b.action==='set_mode'){const mode=String(b.mode||'').toUpperCase();if(!['CLINIC_ONLY','HOSPITAL_ONLY'].includes(mode))return out(res,{error:'invalid_mode'},400);const current=await sql`select mode from public.facility_operating_mode where active=true limit 1`;const previous=current[0]?.mode||null;await sql`update public.facility_operating_mode set active=false where active=true`;const row=await sql`insert into public.facility_operating_mode(mode,changed_by) values(${mode},${staff.id}) returning *`;await sql`insert into public.facility_mode_audit(previous_mode,new_mode,changed_by,reason) values(${previous},${mode},${staff.id},${String(b.reason||'')||null})`;return out(res,{mode:row[0],provider:'appwrite-neon'});}if(b.action==='set_module'){const key=String(b.module_key||'').trim();const enabled=Boolean(b.enabled);const rows=await sql`select * from public.facility_module_registry where module_key=${key} limit 1`;if(!rows[0])return out(res,{error:'module_not_found'},404);if(rows[0].certification_status==='RETIRED')return out(res,{error:'module_retired'},409);const modeRows=await sql`select mode from public.facility_operating_mode where active=true limit 1`;const mode=modeRows[0]?.mode||'CLINIC_ONLY';if(enabled&&((mode==='CLINIC_ONLY'&&!rows[0].clinic_available)||(mode==='HOSPITAL_ONLY'&&!rows[0].hospital_available)))return out(res,{error:'module_not_available_in_mode'},409);if(enabled&&rows[0].certification_status!=='CERTIFIED')return out(res,{error:'module_not_certified'},409);if(enabled&&!(await dependenciesSatisfied(sql,key)))return out(res,{error:'module_dependencies_not_satisfied'},409);const updated=await sql`update public.facility_module_registry set enabled=${enabled},updated_at=now() where module_key=${key} returning *`;return out(res,{module:updated[0],provider:'appwrite-neon'});}return out(res,{error:'unsupported_action'},400);}catch(e){console.error('facility-mode boundary failure',{name:e?.name,message:e?.message});return out(res,{error:'facility_mode_boundary_failure'},500);}}
