import { neon } from '@neondatabase/serverless';
const COOKIE='azaad_admin_appwrite_session';
const MAX=50*1024*1024;
function json(res,b,s=200){res.status(s);res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');return res.json(b)}
function h(req,n){const x=req?.headers;if(typeof x?.get==='function')return String(x.get(n)||'');const k=n.toLowerCase();for(const [a,v] of Object.entries(x||{}))if(a.toLowerCase()===k)return Array.isArray(v)?String(v[0]||''):String(v||'');return ''}
function secret(req){const m=h(req,'cookie').match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]*)`));return m?decodeURIComponent(m[1]):''}
async function auth(req,sql){const endpoint=String(process.env.APPWRITE_ENDPOINT||'').replace(/\/$/,'');const project=String(process.env.APPWRITE_PROJECT_ID||'').trim();const key=String(process.env.APPWRITE_API_KEY||'').trim();const s=secret(req);if(!endpoint||!project||!key||!s)return null;const r=await fetch(`${endpoint}/account`,{headers:{'X-Appwrite-Project':project,'X-Appwrite-Key':key,Cookie:`a_session_${project}=${s}; a_session_${project}_legacy=${s}`,accept:'application/json'}});if(!r.ok)return null;const u=await r.json();const rows=await sql`select id,role,active from public.clinic_staff where auth_user_id=${u.$id} and active=true limit 1`;const staff=rows[0];return staff&&new Set(['OWNER','ADMIN','MANAGER','MARKETING']).has(String(staff.role||'').toUpperCase())?{user:u,staff}:null}
async function readBody(req){if(Buffer.isBuffer(req?.body))return req.body;if(req?.body instanceof Uint8Array)return Buffer.from(req.body);if(typeof req?.body==='string')return Buffer.from(req.body,'binary');const chunks=[];for await(const c of req)chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c));return Buffer.concat(chunks)}
async function appwrite(path,options={}){const endpoint=String(process.env.APPWRITE_ENDPOINT||'').replace(/\/$/,'');const project=String(process.env.APPWRITE_PROJECT_ID||'').trim();const key=String(process.env.APPWRITE_API_KEY||'').trim();if(!endpoint||!project||!key)throw new Error('APPWRITE_RUNTIME_NOT_CONFIGURED');return fetch(`${endpoint}${path}`,{...options,headers:{'X-Appwrite-Project':project,'X-Appwrite-Key':key,accept:'application/json',...(options.headers||{})}})}
async function bucketId(){const configured=String(process.env.AZAAD_APPWRITE_MEDIA_BUCKET_ID||'').trim();if(configured)return configured;const r=await appwrite('/storage/buckets?limit=100');if(!r.ok)throw new Error(`APPWRITE_STORAGE_BUCKETS_${r.status}`);const x=await r.json();const bucket=(x.buckets||[]).find(v=>v.enabled!==false);if(!bucket?.$id)throw new Error('APPWRITE_STORAGE_BUCKET_NOT_FOUND');return bucket.$id}
export default async function handler(req,res){try{const db=String(process.env.DATABASE_URL||'').trim();if(!db)return json(res,{error:'database_not_configured'},503);const sql=neon(db);const a=await auth(req,sql);if(!a)return json(res,{error:'authentication_required'},401);const bucket=await bucketId();if(req.method==='GET'){const id=String(req.query?.file||'').trim();if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,64}$/.test(id))return json(res,{error:'file_required'},400);const r=await appwrite(`/storage/buckets/${encodeURIComponent(bucket)}/files/${encodeURIComponent(id)}/view`,{method:'GET'});if(!r.ok)return json(res,{error:'media_unavailable'},r.status);res.status(r.status);res.setHeader('cache-control','private, max-age=300');res.setHeader('content-type',r.headers.get('content-type')||'application/octet-stream');return res.send(Buffer.from(await r.arrayBuffer()))}
if(req.method!=='POST')return json(res,{error:'method_not_allowed'},405);const length=Number(h(req,'content-length')||0);if(length>MAX)return json(res,{error:'file_too_large'},413);const data=await readBody(req);if(!data.length||data.length>MAX)return json(res,{error:'invalid_file_size'},413);const contentType=(h(req,'content-type')||'application/octet-stream').split(';')[0].trim();if(!/^(image|video)\//.test(contentType))return json(res,{error:'unsupported_media_type'},415);const rawName=decodeURIComponent(h(req,'x-file-name')||'upload');const name=rawName.toLowerCase().replace(/[^a-z0-9._-]/g,'-').slice(-120)||'upload';const fileId=`m-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;const form=new FormData();form.append('file',new Blob([data],{type:contentType}),name);form.append('fileId',fileId);const r=await appwrite(`/storage/buckets/${encodeURIComponent(bucket)}/files`,{method:'POST',body:form});const body=await r.json().catch(()=>({}));if(!r.ok)return json(res,{error:'media_upload_failed',status:r.status},503);return json(res,{fileId:body.$id||fileId,mediaUrl:`/api/marketing-media?file=${encodeURIComponent(body.$id||fileId)}`,mediaType:contentType.startsWith('video/')?'video':'image'})}catch(error){console.error('marketing-media boundary failure',{name:error?.name,message:error?.message});return json(res,{error:'media_unavailable'},503)}}
