import { neon } from '@neondatabase/serverless';
const COOKIE='azaad_admin_appwrite_session'; const ALLOWED=new Set(['OWNER','ADMIN','MANAGER','MARKETING']); const MAX_MEDIA=50*1024*1024;
function json(res,body,status=200){res.status(status);res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');return res.json(body)}
function header(req,name){const h=req?.headers;if(typeof h?.get==='function')return String(h.get(name)||'');const k=String(name).toLowerCase();for(const [n,v] of Object.entries(h||{}))if(String(n).toLowerCase()===k)return Array.isArray(v)?String(v[0]||''):String(v||'');return ''}
function cookie(req){const m=header(req,'cookie').match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]*)`));return m?decodeURIComponent(m[1]):''}
async function body(req){if(typeof req?.json==='function'){const x=await req.json();return x&&typeof x==='object'?x:{}}if(req?.body&&typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;if(typeof req?.body==='string'){try{return JSON.parse(req.body)}catch{}}return {}}
async function rawBody(req){if(Buffer.isBuffer(req?.body))return req.body;if(req?.body instanceof Uint8Array)return Buffer.from(req.body);if(typeof req?.body==='string')return Buffer.from(req.body,'binary');const chunks=[];for await(const c of req)chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c));return Buffer.concat(chunks)}
async function identity(req,sql){const endpoint=String(process.env.APPWRITE_ENDPOINT||'').replace(/\/$/,'');const project=String(process.env.APPWRITE_PROJECT_ID||'').trim();const key=String(process.env.APPWRITE_API_KEY||'').trim();const secret=cookie(req);if(!endpoint||!project||!key||!secret)return null;const r=await fetch(`${endpoint}/account`,{headers:{'X-Appwrite-Project':project,'X-Appwrite-Key':key,Cookie:`a_session_${project}=${secret}; a_session_${project}_legacy=${secret}`,accept:'application/json'}});if(!r.ok)return null;const user=await r.json();const rows=await sql`select id,auth_user_id,full_name,username,email,phone,role,active from public.clinic_staff where auth_user_id=${user.$id} and active=true limit 1`;const staff=rows[0];const role=String(staff?.role||'').toUpperCase();return staff&&ALLOWED.has(role)?{user,staff,role}:null}
async function appwrite(path,options={}){const endpoint=String(process.env.APPWRITE_ENDPOINT||'').replace(/\/$/,'');const project=String(process.env.APPWRITE_PROJECT_ID||'').trim();const key=String(process.env.APPWRITE_API_KEY||'').trim();if(!endpoint||!project||!key)throw new Error('APPWRITE_RUNTIME_NOT_CONFIGURED');return fetch(`${endpoint}${path}`,{...options,headers:{'X-Appwrite-Project':project,'X-Appwrite-Key':key,accept:'application/json',...(options.headers||{})}})}
async function bucketId(){const configured=String(process.env.AZAAD_APPWRITE_MEDIA_BUCKET_ID||'').trim();if(configured)return configured;const r=await appwrite('/storage/buckets?limit=100');if(!r.ok)throw new Error(`APPWRITE_STORAGE_BUCKETS_${r.status}`);const x=await r.json();const bucket=(x.buckets||[]).find(v=>v.enabled!==false);if(!bucket?.$id)throw new Error('APPWRITE_STORAGE_BUCKET_NOT_FOUND');return bucket.$id}
function queryType(req){const fromHeader=header(req,'x-azaad-query').trim().toLowerCase();if(fromHeader)return fromHeader;try{return new URL(String(req.url||'/'),'http://localhost').searchParams.get('type')||'channels'}catch{return 'channels'}}
export default async function handler(req,res){try{const db=String(process.env.DATABASE_URL||'').trim();if(!db)return json(res,{error:'database_not_configured'},503);const sql=neon(db);const auth=await identity(req,sql);if(!auth)return json(res,{error:'authentication_required'},401);const type=queryType(req);
if(req.method==='GET'){if(type==='campaigns'){const rows=await sql`select * from public.clinic_marketing_campaigns order by created_at desc limit 100`;return json(res,{campaigns:rows})}if(type==='posts'){const rows=await sql`select * from public.clinic_marketing_posts order by created_at desc limit 100`;return json(res,{posts:rows})}if(type==='media'){const id=String(new URL(String(req.url||'/'),'http://localhost').searchParams.get('file')||'').trim();if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,64}$/.test(id))return json(res,{error:'file_required'},400);const bucket=await bucketId();const r=await appwrite(`/storage/buckets/${encodeURIComponent(bucket)}/files/${encodeURIComponent(id)}/view`,{method:'GET'});if(!r.ok)return json(res,{error:'media_unavailable'},r.status);res.status(r.status);res.setHeader('cache-control','private, max-age=300');res.setHeader('content-type',r.headers.get('content-type')||'application/octet-stream');return res.send(Buffer.from(await r.arrayBuffer()))}const rows=await sql`select * from public.clinic_marketing_channels where active=true order by is_builtin desc,display_name_en`;return json(res,{channels:rows})}
if(req.method!=='POST')return json(res,{error:'method_not_allowed'},405);if(type==='upload_media'){const length=Number(header(req,'content-length')||0);if(length>MAX_MEDIA)return json(res,{error:'file_too_large'},413);const data=await rawBody(req);if(!data.length||data.length>MAX_MEDIA)return json(res,{error:'invalid_file_size'},413);const contentType=(header(req,'content-type')||'application/octet-stream').split(';')[0].trim();if(!/^(image|video)\//.test(contentType))return json(res,{error:'unsupported_media_type'},415);const rawName=decodeURIComponent(header(req,'x-file-name')||'upload');const name=rawName.toLowerCase().replace(/[^a-z0-9._-]/g,'-').slice(-120)||'upload';const fileId=`m-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;const form=new FormData();form.append('file',new Blob([data],{type:contentType}),name);form.append('fileId',fileId);const bucket=await bucketId();const r=await appwrite(`/storage/buckets/${encodeURIComponent(bucket)}/files`,{method:'POST',body:form});const b=await r.json().catch(()=>({}));if(!r.ok)return json(res,{error:'media_upload_failed'},503);return json(res,{fileId:b.$id||fileId,mediaUrl:`/api/marketing?type=media&file=${encodeURIComponent(b.$id||fileId)}`,mediaType:contentType.startsWith('video/')?'video':'image'})}
const b=await body(req);const action=String(b.action||'').trim();if(action==='create_post'){const title=String(b.title||'').trim().slice(0,200);const content=String(b.content||'').trim().slice(0,20000);if(!title&&!content)return json(res,{error:'content_required'},400);const status=b.status==='READY'?'ready':'draft';const mediaUrl=String(b.media_url||'').trim().slice(0,1000)||null;const mediaType=String(b.media_type||'none').slice(0,20);const rows=await sql`insert into public.clinic_marketing_posts(title,content,media_url,media_type,platform,status,ai_caption,created_by) values(${title},${content},${mediaUrl},${mediaType},'multi',${status},${content},${auth.staff.id}) returning id,title,content,media_url,media_type,platform,status,created_at`;const ids=Array.isArray(b.channel_ids)?b.channel_ids.filter(validUuid).slice(0,20):[];for(const channelId of ids)await sql`insert into public.clinic_marketing_publications(post_id,channel_id,status,created_by) values(${rows[0].id},${channelId},'ready',${auth.staff.id}) on conflict(post_id,channel_id,campaign_id) do update set status='ready',updated_at=now()`;return json(res,{post:rows[0]})}
if(action==='create_campaign'){const name=String(b.name||'').trim().slice(0,200);if(!name)return json(res,{error:'name_required'},400);const objective=String(b.objective||'awareness').slice(0,40);const rows=await sql`insert into public.clinic_marketing_campaigns(name,objective,status,start_at,end_at,budget,budget_currency,created_by) values(${name},${objective},'draft',${b.start_at||null},${b.end_at||null},${b.budget||null},'EGP',${auth.staff.id}) returning *`;const ids=Array.isArray(b.channel_ids)?b.channel_ids.filter(validUuid).slice(0,20):[];for(const channelId of ids)await sql`insert into public.clinic_marketing_campaign_channels(campaign_id,channel_id,status) values(${rows[0].id},${channelId},'planned') on conflict(campaign_id,channel_id) do nothing`;return json(res,{campaign:rows[0]})}
if(action==='add_channel'){const platform=String(b.platform_key||'').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,50);const ar=String(b.display_name_ar||'').trim().slice(0,100);const en=String(b.display_name_en||'').trim().slice(0,100);if(!platform||!en)return json(res,{error:'channel_required'},400);const rows=await sql`insert into public.clinic_marketing_channels(platform_key,display_name_ar,display_name_en,icon,account_url,active,is_builtin,created_by) values(${platform},${ar||en},${en},${String(b.icon||'🌐').slice(0,8)},${String(b.account_url||'').trim().slice(0,500)||null},true,false,${auth.staff.id}) on conflict(platform_key) do update set active=true,display_name_ar=excluded.display_name_ar,display_name_en=excluded.display_name_en,icon=excluded.icon,account_url=excluded.account_url,updated_at=now() returning *`;return json(res,{channel:rows[0]})}
return json(res,{error:'unsupported_action'},400)}catch(error){console.error('marketing boundary failure',{name:error?.name,message:error?.message});return json(res,{error:'marketing_unavailable'},503)}}
