import { neon } from '@neondatabase/serverless';

const COOKIE='azaad_admin_appwrite_session';
const ROLES=new Set(['OWNER','ADMIN','MANAGER','SECRETARY','RECEPTION','DOCTOR']);
const WRITE_ROLES=new Set(['OWNER','ADMIN','MANAGER','SECRETARY','RECEPTION','DOCTOR']);
function json(res,body,status=200){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(body));}
function cookieValue(req){const raw=req.headers.cookie||'';const m=raw.match(new RegExp(`(?:^|;\\s*)${COOKIE}=([^;]*)`));return m?decodeURIComponent(m[1]):'';}
async function account(secret){const endpoint=String(process.env.APPWRITE_ENDPOINT||'').replace(/\/$/,'');const project=String(process.env.APPWRITE_PROJECT_ID||'').trim();if(!endpoint||!project||!secret)return null;const r=await fetch(`${endpoint}/account`,{headers:{'X-Appwrite-Project':project,accept:'application/json',Cookie:`a_session_${project}=${secret}; a_session_${project}_legacy=${secret}`}});return r.ok?r.json():null;}
async function auth(req){const user=await account(cookieValue(req));if(!user?.$id)return null;const url=String(process.env.DATABASE_URL||'').trim();if(!url)return null;const sql=neon(url);const rows=await sql`select id,auth_user_id,full_name,role,active,doctor_id from public.clinic_staff where auth_user_id=${user.$id} and active=true limit 1`;const staff=rows[0];const role=String(staff?.role||'').toUpperCase();return staff&&ROLES.has(role)?{user,staff,role,sql}:null;}
function canDoctor(identity,doctorId){return identity.role!=='DOCTOR'||String(identity.staff.doctor_id||'')===String(doctorId||'');}
async function body(req){if(req.body&&typeof req.body==='object')return req.body;let raw='';for await(const c of req)raw+=c;try{return raw?JSON.parse(raw):{}}catch{return null;}}
export default async function handler(req,res){try{const identity=await auth(req);if(!identity)return json(res,{error:'authentication_required'},401);const u=new URL(req.url,`https://${req.headers.host||'localhost'}`);const resource=String(u.searchParams.get('resource')||'').toLowerCase();
if(req.method==='GET'&&resource==='doctors'){const rows=await identity.sql`select id,name,title from public.clinic_doctors where active=true and (${identity.role} <> 'DOCTOR' or id=${identity.staff.doctor_id}::uuid) order by sort_order,name`;return json(res,{doctors:rows,provider:'appwrite-neon'});}
if(req.method==='GET'&&resource==='patients'){const q=String(u.searchParams.get('search')||'').trim();if(q.length<2)return json(res,{patients:[]});const like=`%${q.replace(/[%_]/g,'')}%`;const rows=await identity.sql`select id,mrn,patient_name,patient_phone from public.clinic_patients where active=true and (patient_name ilike ${like} or mrn ilike ${like} or patient_phone ilike ${like} or patient_phone_normalized ilike ${like}) order by created_at desc limit 20`;return json(res,{patients:rows,provider:'appwrite-neon'});}
if(req.method==='GET'&&resource==='entries'){const date=String(u.searchParams.get('date')||'').trim();const requestedDoctor=String(u.searchParams.get('doctor_id')||'').trim();if(!date)return json(res,{error:'date_required'},400);if(identity.role==='DOCTOR'&&!canDoctor(identity,requestedDoctor||identity.staff.doctor_id))return json(res,{error:'forbidden'},403);const doctor=requestedDoctor||(identity.role==='DOCTOR'?String(identity.staff.doctor_id||''):'');const rows=await identity.sql`select w.id,w.patient_id,w.doctor_id,w.service_id,w.requested_date,w.preferred_start_time,w.preferred_end_time,w.priority,w.status,w.position,w.reason,w.patient_phone_snapshot,w.source,w.notes,w.created_at,w.contacted_at,w.confirmed_at,p.patient_name,p.mrn,p.patient_phone,d.name as doctor_name,d.title as doctor_title from public.clinic_waiting_list w left join public.clinic_patients p on p.id=w.patient_id left join public.clinic_doctors d on d.id=w.doctor_id where w.requested_date=${date}::date and (${doctor}='' or w.doctor_id=${doctor}::uuid) order by w.position,w.created_at`;return json(res,{entries:rows,provider:'appwrite-neon'});}
if(req.method==='POST'){if(!WRITE_ROLES.has(identity.role))return json(res,{error:'forbidden'},403);const b=await body(req);if(!b)return json(res,{error:'invalid_json'},400);if(String(b.action||'')!=='create')return json(res,{error:'unsupported_action'},400);const patientId=String(b.patient_id||'').trim(),doctor=String(b.doctor_id||'').trim(),date=String(b.requested_date||'').trim(),priority=String(b.priority||'normal').trim();if(!patientId||!doctor||!date)return json(res,{error:'patient_doctor_date_required'},400);if(!canDoctor(identity,doctor))return json(res,{error:'forbidden'},403);if(!['normal','urgent','emergency'].includes(priority))return json(res,{error:'invalid_priority'},400);const patient=await identity.sql`select id,patient_phone from public.clinic_patients where id=${patientId}::uuid and active=true limit 1`;if(!patient[0])return json(res,{error:'patient_not_found'},404);const doctorRow=await identity.sql`select id from public.clinic_doctors where id=${doctor}::uuid and active=true limit 1`;if(!doctorRow[0])return json(res,{error:'doctor_not_found'},404);const positionRows=await identity.sql`select coalesce(max(position),0)+1 as position from public.clinic_waiting_list where doctor_id=${doctor}::uuid and requested_date=${date}::date and status in ('pending','contacted')`;const position=Number(positionRows[0]?.position||1);const rows=await identity.sql`insert into public.clinic_waiting_list(patient_id,doctor_id,preferred_doctor_id,requested_date,priority,reason,notes,patient_phone_snapshot,position,source,status,created_at) values(${patientId}::uuid,${doctor}::uuid,${doctor}::uuid,${date}::date,${priority},${b.reason?String(b.reason).trim():null},${b.notes?String(b.notes).trim():null},${patient[0].patient_phone||null},${position},${identity.role==='DOCTOR'?'doctor':'frontdesk'},'pending',now()) returning *`;return json(res,{entry:rows[0],provider:'appwrite-neon'},201);}
if(req.method==='PATCH'){if(!WRITE_ROLES.has(identity.role))return json(res,{error:'forbidden'},403);const b=await body(req);if(!b)return json(res,{error:'invalid_json'},400);const id=String(b.id||'').trim(),status=String(b.status||'').trim();if(!id||!['contacted','cancelled','confirmed','converted','expired','no_show'].includes(status))return json(res,{error:'invalid_status'},400);const target=await identity.sql`select id,doctor_id from public.clinic_waiting_list where id=${id}::uuid limit 1`;if(!target[0])return json(res,{error:'waiting_entry_not_found'},404);if(!canDoctor(identity,target[0].doctor_id))return json(res,{error:'forbidden'},403);const rows=await identity.sql`update public.clinic_waiting_list set status=${status},contacted_at=${status==='contacted'?new Date().toISOString():null},confirmed_at=${status==='confirmed'?new Date().toISOString():null},updated_at=now() where id=${id}::uuid returning *`;return json(res,{entry:rows[0],provider:'appwrite-neon'});}
return json(res,{error:'method_not_allowed'},405);
}catch(error){console.error('waiting-list boundary failure',{name:error?.name,message:error?.message});return json(res,{error:'waiting_list_unavailable'},503)}}
