from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
path=ROOT/'api'/'admin-appointments.js'
text=path.read_text(encoding='utf-8')
marker="if(resource==='services'||resource==='doctor-services'){"
if text.count(marker)!=1: raise SystemExit('FAIL-CLOSED: scheduling boundary marker count != 1')
if "resource==='scheduling'" in text: raise SystemExit('FAIL-CLOSED: duplicate scheduling boundary injection detected')
branch=r'''if(resource==='scheduling'){
  const readRoles=['OWNER','ADMIN','MANAGER','SECRETARY','RECEPTION','DOCTOR'];
  if(!readRoles.includes(identity.role))return json(res,{error:'forbidden'},403);
  const table=String(url.searchParams.get('table')||'').toLowerCase();
  if(req.method==='GET'){
    const from=String(url.searchParams.get('from')||'').trim(),to=String(url.searchParams.get('to')||'').trim();
    if(table==='doctors'){const rows=await identity.sql`select id,name,title,image_url,active from public.clinic_doctors where active=true order by sort_order nulls last,name`;return json(res,{rows,provider:'appwrite-neon'});}
    if(table==='services'){const rows=await identity.sql`select id,name,duration_minutes,active from public.clinic_services where active=true order by sort_order nulls last,name`;return json(res,{rows,provider:'appwrite-neon'});}
    if(table==='bookings'){if(!from||!to)return json(res,{error:'date_range_required'},400);const rows=await identity.sql`select b.id,b.booking_code,b.doctor_id,b.service_id,b.patient_id,b.patient_name,b.patient_phone,b.appointment_date,b.appointment_time,b.status,b.mode,b.notes from public.clinic_bookings b where b.appointment_date between ${from}::date and ${to}::date and coalesce(b.booking_code,'') not ilike 'E2E-%' order by b.appointment_date,b.appointment_time limit 500`;return json(res,{rows,provider:'appwrite-neon'});}
    if(table==='schedules'){const rows=await identity.sql`select doctor_id,weekday,enabled,start_time,end_time,break_start,break_end,slot_minutes,buffer_minutes,max_daily_bookings from public.doctor_weekly_schedules`;return json(res,{rows,provider:'appwrite-neon'});}
    if(table==='overrides'){if(!from||!to)return json(res,{error:'date_range_required'},400);const rows=await identity.sql`select doctor_id,override_date,type,start_time,end_time,break_start,break_end,slot_minutes,max_daily_bookings from public.doctor_schedule_overrides where override_date between ${from}::date and ${to}::date`;return json(res,{rows,provider:'appwrite-neon'});}
    if(table==='waiting'){const rows=await identity.sql`select id,patient_id,doctor_id,preferred_doctor_id,alternative_doctor_ids,service_id,requested_date,preferred_start_time,preferred_end_time,priority,reason,patient_phone_snapshot,status,position,source,notes,created_at from public.clinic_waiting_list where status in ('waiting','pending','active') order by position nulls last,created_at`;return json(res,{rows,provider:'appwrite-neon'});}
    if(table==='patients'){const q=String(url.searchParams.get('q')||'').trim().replace(/[%(),]/g,' ');if(!q)return json(res,{rows:[],provider:'appwrite-neon'});const rows=await identity.sql`select id,mrn,patient_name,patient_phone,active from public.clinic_patients where active=true and (mrn ilike ${`%${q}%`} or patient_name ilike ${`%${q}%`} or patient_phone ilike ${`%${q}%`}) order by created_at desc limit 12`;return json(res,{rows,provider:'appwrite-neon'});}
    return json(res,{error:'unsupported_scheduling_table'},400);
  }
  if(req.method!=='POST')return json(res,{error:'method_not_allowed'},405);
  let body={};try{body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});}catch{return json(res,{error:'invalid_json'},400);}
  const action=String(body.action||'').toUpperCase();
  if(['BOOK','RESCHEDULE','TRANSFER','CANCEL','NO_SHOW','ADD_WAITING','ASSIGN_WAITING'].includes(action) && !['OWNER','ADMIN','MANAGER','SECRETARY','RECEPTION'].includes(identity.role))return json(res,{error:'forbidden'},403);
  if(action==='BOOK'){
    const patientId=String(body.patient_id||''),doctorId=String(body.doctor_id||''),serviceId=String(body.service_id||'');if(!patientId||!doctorId||!serviceId||!body.appointment_date||!body.appointment_time)return json(res,{error:'booking_fields_required'},400);
    const [patient,doctor,service]=await Promise.all([identity.sql`select id,patient_name,patient_phone from public.clinic_patients where id=${patientId}::uuid and active=true limit 1`,identity.sql`select id,name from public.clinic_doctors where id=${doctorId}::uuid and active=true limit 1`,identity.sql`select id,price from public.clinic_services where id=${serviceId}::uuid and active=true limit 1`]);if(!patient[0]||!doctor[0]||!service[0])return json(res,{error:'booking_reference_not_found'},404);
    const conflict=await identity.sql`select id from public.clinic_bookings where doctor_id=${doctor[0].id} and appointment_date=${body.appointment_date}::date and appointment_time=${body.appointment_time}::time and upper(coalesce(status,'')) not in ('CANCELLED','NO_SHOW') limit 1`;if(conflict[0])return json(res,{error:'slot_unavailable'},409);
    const code=`AZA-${Date.now().toString(36).toUpperCase()}`;const b=await identity.sql`insert into public.clinic_bookings(booking_code,patient_id,patient_name,patient_phone,doctor_id,service_id,appointment_date,appointment_time,status,payment_status,notes,created_at,updated_at) values(${code},${patient[0].id},${patient[0].patient_name},${patient[0].patient_phone},${doctor[0].id},${service[0].id},${body.appointment_date},${body.appointment_time},'scheduled','unpaid',${body.notes?String(body.notes):null},now(),now()) returning id,booking_code,patient_id,doctor_id,service_id,appointment_date,appointment_time,status,payment_status`;return json(res,{booking:b[0],provider:'appwrite-neon'},201);
  }
  if(action==='CANCEL'||action==='NO_SHOW'){const id=String(body.booking_id||'');if(!id)return json(res,{error:'booking_id_required'},400);const status=action==='CANCEL'?'cancelled':'no_show';const rows=await identity.sql`update public.clinic_bookings set status=${status},updated_at=now() where id=${id}::uuid and upper(coalesce(status,'')) not in ('CANCELLED','COMPLETED') returning id,status,appointment_date,appointment_time`;if(!rows[0])return json(res,{error:'booking_not_found_or_closed'},404);return json(res,{booking:rows[0],provider:'appwrite-neon'});}
  if(action==='RESCHEDULE'){const id=String(body.booking_id||'');if(!id||!body.appointment_date||!body.appointment_time)return json(res,{error:'reschedule_fields_required'},400);const current=await identity.sql`select id,doctor_id,status from public.clinic_bookings where id=${id}::uuid limit 1`;if(!current[0])return json(res,{error:'booking_not_found'},404);if(['CANCELLED','COMPLETED','NO_SHOW'].includes(String(current[0].status||'').toUpperCase()))return json(res,{error:'booking_closed'},409);const conflict=await identity.sql`select id from public.clinic_bookings where doctor_id=${current[0].doctor_id} and appointment_date=${body.appointment_date}::date and appointment_time=${body.appointment_time}::time and id<>${id}::uuid and upper(coalesce(status,'')) not in ('CANCELLED','NO_SHOW') limit 1`;if(conflict[0])return json(res,{error:'slot_unavailable'},409);const rows=await identity.sql`update public.clinic_bookings set appointment_date=${body.appointment_date},appointment_time=${body.appointment_time},updated_at=now() where id=${id}::uuid returning id,appointment_date,appointment_time,status`;return json(res,{booking:rows[0],provider:'appwrite-neon'});}
  if(action==='TRANSFER'){const id=String(body.booking_id||''),doctorId=String(body.doctor_id||'');if(!id||!doctorId)return json(res,{error:'transfer_fields_required'},400);const doctor=await identity.sql`select id from public.clinic_doctors where id=${doctorId}::uuid and active=true limit 1`;if(!doctor[0])return json(res,{error:'doctor_not_found'},404);const current=await identity.sql`select id,appointment_date,appointment_time,status from public.clinic_bookings where id=${id}::uuid limit 1`;if(!current[0])return json(res,{error:'booking_not_found'},404);const conflict=await identity.sql`select id from public.clinic_bookings where doctor_id=${doctor[0].id} and appointment_date=${current[0].appointment_date} and appointment_time=${current[0].appointment_time} and id<>${id}::uuid and upper(coalesce(status,'')) not in ('CANCELLED','NO_SHOW') limit 1`;if(conflict[0])return json(res,{error:'slot_unavailable'},409);const rows=await identity.sql`update public.clinic_bookings set doctor_id=${doctor[0].id},updated_at=now() where id=${id}::uuid returning id,doctor_id,appointment_date,appointment_time,status`;return json(res,{booking:rows[0],provider:'appwrite-neon'});}
  if(action==='ADD_WAITING'){const patientId=String(body.patient_id||'');if(!patientId||!body.service_id)return json(res,{error:'waiting_fields_required'},400);const patient=await identity.sql`select id,patient_phone from public.clinic_patients where id=${patientId}::uuid and active=true limit 1`;if(!patient[0])return json(res,{error:'patient_not_found'},404);const pos=await identity.sql`select coalesce(max(position),0)+1 as position from public.clinic_waiting_list where status in ('waiting','pending','active')`;const rows=await identity.sql`insert into public.clinic_waiting_list(patient_id,preferred_doctor_id,service_id,requested_date,priority,reason,patient_phone_snapshot,status,position,source,created_at) values(${patient[0].id},${body.preferred_doctor_id?String(body.preferred_doctor_id):null},${String(body.service_id)},${body.requested_date||null},${String(body.priority||'normal')},${body.reason?String(body.reason):null},${patient[0].patient_phone},'waiting',${Number(pos[0].position)},'admin',now()) returning id,patient_id,preferred_doctor_id,service_id,requested_date,priority,status,position`;return json(res,{waiting:rows[0],provider:'appwrite-neon'},201);}
  if(action==='ASSIGN_WAITING'){const waitingId=String(body.waiting_id||''),doctorId=String(body.doctor_id||'');if(!waitingId||!body.appointment_date||!body.appointment_time)return json(res,{error:'assign_fields_required'},400);const w=await identity.sql`select id,patient_id,service_id,preferred_doctor_id,status from public.clinic_waiting_list where id=${waitingId}::uuid and status in ('waiting','pending','active') limit 1`;if(!w[0])return json(res,{error:'waiting_not_found'},404);const did=doctorId||w[0].preferred_doctor_id;if(!did)return json(res,{error:'doctor_required'},400);const conflict=await identity.sql`select id from public.clinic_bookings where doctor_id=${did}::uuid and appointment_date=${body.appointment_date}::date and appointment_time=${body.appointment_time}::time and upper(coalesce(status,'')) not in ('CANCELLED','NO_SHOW') limit 1`;if(conflict[0])return json(res,{error:'slot_unavailable'},409);const patient=await identity.sql`select patient_name,patient_phone from public.clinic_patients where id=${w[0].patient_id}::uuid and active=true limit 1`;if(!patient[0])return json(res,{error:'patient_not_found'},404);const code=`WAIT-${Date.now().toString(36).toUpperCase()}`;const b=await identity.sql`insert into public.clinic_bookings(booking_code,patient_id,patient_name,patient_phone,doctor_id,service_id,appointment_date,appointment_time,status,payment_status,created_at,updated_at) values(${code},${w[0].patient_id},${patient[0].patient_name},${patient[0].patient_phone},${did}::uuid,${w[0].service_id},${body.appointment_date},${body.appointment_time},'scheduled','unpaid',now(),now()) returning id,booking_code,appointment_date,appointment_time,status`;await identity.sql`update public.clinic_waiting_list set status='assigned',updated_at=now() where id=${waitingId}::uuid`;return json(res,{booking:b[0],waiting_id:waitingId,provider:'appwrite-neon'},201);}
  return json(res,{error:'unsupported_scheduling_action'},400);
}
'''
path.write_text(text.replace(marker,branch+marker,1),encoding='utf-8')
print('PASS: scheduling resource consolidated into admin-appointments Appwrite-Neon boundary')