from pathlib import Path
import textwrap

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'clinician-ai-session-cockpit.js'

if not TARGET.is_file():
    raise SystemExit('FAIL-CLOSED: clinician AI cockpit source is missing')

JS = textwrap.dedent(r'''\
(() => {
  'use strict';
  if (window.__AZAAD_CLINICIAN_AI_COCKPIT__) return;
  window.__AZAAD_CLINICIAN_AI_COCKPIT__ = true;
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const patientId = () => window.CURRENT_PATIENT_ID || window.patientId || new URLSearchParams(location.search).get('patient_id') || document.body.dataset.patientId || '';
  const visitId = () => window.CURRENT_VISIT_ID || new URLSearchParams(location.search).get('visit_id') || document.body.dataset.visitId || '';
  const lang = () => String(document.documentElement.lang || 'ar').toLowerCase().startsWith('en') ? 'en' : 'ar';
  const C = {
    ar:{title:'🧠 المساعد السريري للجلسة',sub:'مساحة سريرية سريعة للطبيب/المعالج — القرار السريري للطبيب دائمًا.',start:'بدء التقييم',finish:'حفظ وإنهاء التقييم',add:'➕ سؤال محلي',suggest:'🤖 اقتراح موعد',score:'النسبة الحالية',trend:'الاتجاه',baseline:'خط الأساس',previous:'الزيارة السابقة',improving:'🟢 مؤشرات تحسن',stable:'🟡 مستقرة/مختلطة',worsening:'🔴 توجد مؤشرات تراجع',insufficient:'⚪ بيانات غير كافية',source:'📚 المصدر',note:'ملاحظة الطبيب/المعالج',yes:'✅ نعم / موجود',no:'❌ لا / غير موجود',skip:'⚪ غير مُقيّم',safety:'⚠️ تنبيهات الأمان تحتاج مراجعة الطبيب واتباع بروتوكول العيادة المعتمد.',loading:'جاري تحميل الأسئلة...',failed:'تعذر تحميل التقييم.',noPatient:'لم يتم تحديد المريض.',saved:'✅ تم الحفظ',complete:'اكتمل التقييم'},
    en:{title:'🧠 Clinical Session Copilot',sub:'A focused clinician workspace — the clinician remains responsible for clinical decisions.',start:'Start assessment',finish:'Save & finish assessment',add:'➕ Local question',suggest:'🤖 Suggest follow-up',score:'Current score',trend:'Trend',baseline:'Baseline',previous:'Previous visit',improving:'🟢 Improving',stable:'🟡 Stable / mixed',worsening:'🔴 Worsening',insufficient:'⚪ Insufficient data',source:'📚 Source',note:'Clinician note',yes:'✅ Yes / Present',no:'❌ No / Absent',skip:'⚪ Not assessed',safety:'⚠️ Safety alerts require clinician review and the clinic-approved safety protocol.',loading:'Loading questions...',failed:'Unable to load assessment.',noPatient:'Patient is not selected.',saved:'✅ Saved',complete:'Assessment complete'}
  };
  let state={answers:{},notes:'',started:false,templateId:'',templateName:'',questions:[],baseline:null,previous:null};
  const key=()=>`azaad_clinical_session_draft:${patientId()}:${visitId()||'new'}`;
  const read=async url=>{const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{Accept:'application/json'}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||`HTTP ${r.status}`);return b;};
  const write=async body=>{const r=await fetch('/api/clinical-assessments',{method:'POST',credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||`HTTP ${r.status}`);return b;};
  const saveDraft=()=>{try{sessionStorage.setItem(key(),JSON.stringify(state))}catch(_){}};
  const loadDraft=()=>{try{const x=sessionStorage.getItem(key());if(x)state={...state,...JSON.parse(x)}}catch(_){}};
  const score=()=>{const a=Object.values(state.answers).filter(v=>v==='yes'||v==='no');return a.length?Math.round(a.filter(v=>v==='yes').length/a.length*100):null};
  const trendCode=s=>{if(s==null)return'insufficient';if(state.previous==null)return s>=70?'improving':s>=45?'stable':'worsening';const d=s-state.previous;return d>=10?'improving':d<=-10?'worsening':'stable'};
  const toast=m=>{let t=$('azaadAiToast');if(!t){t=document.createElement('div');t.id='azaadAiToast';t.style.cssText='position:fixed;bottom:18px;left:18px;right:18px;max-width:560px;margin:auto;background:#18213d;color:#fff;padding:12px 16px;border-radius:12px;z-index:9999;text-align:center';document.body.appendChild(t)}t.textContent=m;t.hidden=false;clearTimeout(t.__timer);t.__timer=setTimeout(()=>t.hidden=true,2600)};
  async function loadData(){const c=C[lang()];if(!patientId())throw Error(c.noPatient);const b=await read('/api/clinical-assessments?action=templates');const ts=b.templates||[],qs=b.questions||[],chosen=ts.find(x=>x.id===state.templateId)||ts[0];if(!chosen)throw Error(c.failed);state.templateId=chosen.id;state.templateName=lang()==='en'?(chosen.name||chosen.name_ar):(chosen.name_ar||chosen.name);state.questions=qs.filter(q=>q.template_id===state.templateId);const h=await read(`/api/clinical-assessments?action=history&patient_id=${encodeURIComponent(patientId())}${visitId()?`&visit_id=${encodeURIComponent(visitId())}`:''}`);const prior=h.sessions||[];state.previous=prior[0]?.score_percent??null;state.baseline=prior.length?prior[prior.length-1]?.score_percent??null:null;}
  function metrics(){const c=C[lang()],s=score(),code=trendCode(s);$('aiScore').textContent=s==null?'—':`${s}%`;$('aiTrend').textContent=c[code];$('aiBaseline').textContent=state.baseline==null?'—':`${state.baseline}%`;$('aiPrevious').textContent=state.previous==null?'—':`${state.previous}%`;$('aiTemplateName').textContent=state.templateName||'';}
  function renderQuestions(){const w=$('aiQuestions'),c=C[lang()];if(!w)return;w.innerHTML=state.questions.map(q=>{const a=state.answers[q.id]||'',text=lang()==='en'?(q.question_text||q.question_text_ar):(q.question_text_ar||q.question_text);return `<article style="border:1px solid #e2e8f0;border-radius:16px;padding:14px;margin:10px 0;background:#fff"><span style="font-size:11px;background:#edf3ff;padding:4px 8px;border-radius:12px">${esc(q.category||'Clinical')}</span><h3 style="margin:9px 0">${esc(text)}</h3><div style="font-size:12px;color:#7a8498">${c.source}: ${esc(q.source_title||'Azaad Clinic clinical library')}</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn ${a==='yes'?'btn-success':'btn-secondary'}" data-ai-q="${esc(q.id)}" data-ai-v="yes">${c.yes}</button><button class="btn ${a==='no'?'btn-danger':'btn-secondary'}" data-ai-q="${esc(q.id)}" data-ai-v="no">${c.no}</button><button class="btn btn-secondary" data-ai-q="${esc(q.id)}" data-ai-v="skip">${c.skip}</button></div></article>`}).join('')||`<div style="padding:20px;text-align:center">${c.failed}</div>`;w.querySelectorAll('[data-ai-q]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.aiV==='skip')delete state.answers[b.dataset.aiQ];else state.answers[b.dataset.aiQ]=b.dataset.aiV;state.started=true;saveDraft();metrics();renderQuestions()}));}
  function add(){const text=prompt(lang()==='en'?'Enter a clinician-authored local question:':'اكتب سؤالًا محليًا من تأليف الطبيب/المعالج:');if(!text?.trim())return;state.questions.push({id:`local_${Date.now()}`,question_text:text.trim(),question_text_ar:text.trim(),category:'custom',source_title:'Clinician-authored local'});renderQuestions();}
  function suggest(){document.querySelector('#doctorFollowupWidget')?.scrollIntoView({behavior:'smooth',block:'center'});}
  async function finish(){state.notes=$('aiNote')?.value||'';const answers=Object.entries(state.answers).map(([question_id,v])=>({question_id,response_boolean:v==='yes'?true:v==='no'?false:null,response_text:null}));try{const result=await write({patient_id:patientId(),clinical_visit_id:visitId(),template_id:state.templateId,answers,clinician_notes:state.notes});state.started=false;saveDraft();toast(`${C[lang()].complete} — ${result.percentage??score()??'—'}%`)}catch(e){toast(`❌ ${e.message}`)}}
  function render(){const host=document.querySelector('#clinicalAssessmentApp')||document.querySelector('#patient360')||document.querySelector('main');if(!host||$('azaadClinicianAICockpit'))return;loadDraft();const c=C[lang()],box=document.createElement('section');box.id='azaadClinicianAICockpit';box.style.cssText='margin:18px 0;border-radius:20px;padding:18px;background:linear-gradient(135deg,#f7fbff,#fff);border:1px solid #dbe6f4;box-shadow:0 10px 35px rgba(24,33,61,.07)';box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap"><div><h2 style="margin:0 0 6px">${c.title}</h2><div style="color:#68738a">${c.sub}</div><div id="aiTemplateName" style="margin-top:6px;font-weight:700"></div></div><button id="aiStart" class="btn btn-primary">${c.start}</button></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0"><div class="card"><b>${c.score}</b><div id="aiScore" style="font-size:30px;font-weight:900">—</div></div><div class="card"><b>${c.trend}</b><div id="aiTrend">${c.insufficient}</div></div><div class="card"><b>${c.baseline}</b><div id="aiBaseline">—</div></div><div class="card"><b>${c.previous}</b><div id="aiPrevious">—</div></div></div><div id="aiQuestions"><div style="padding:20px;text-align:center">${c.loading}</div></div><label style="display:block;font-weight:700">${c.note}<textarea id="aiNote" rows="3" style="width:100%;margin-top:7px"></textarea></label><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button id="aiAdd" class="btn btn-secondary">${c.add}</button><button id="aiSuggest" class="btn btn-secondary">${c.suggest}</button><button id="aiFinish" class="btn btn-primary">${c.finish}</button></div><div style="margin-top:12px;padding:10px;border-radius:12px;background:#fff8e6;color:#6b5700">${c.safety}</div>`;host.prepend(box);$('aiStart').onclick=()=>{state.started=true;saveDraft();metrics();renderQuestions()};$('aiFinish').onclick=finish;$('aiAdd').onclick=add;$('aiSuggest').onclick=suggest;loadData().then(()=>{renderQuestions();metrics()}).catch(e=>{$('aiQuestions').innerHTML=`<div style="padding:20px;text-align:center;color:#a32939">❌ ${esc(e.message||c.failed)}</div>`})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',render,{once:true}):render();
})();
''')
TARGET.write_text(JS, encoding='utf-8')
for marker in ('SUPABASE_URL','SUPABASE_PUBLISHABLE_KEY','supabase.co','functions/v1/','supabase.auth'):
    if marker.lower() in JS.lower():
        raise SystemExit(f'FAIL-CLOSED: retired marker remained in canonical clinician AI cockpit: {marker}')
print('[AZAAD clinician AI cockpit] PASS: canonical Appwrite/Neon same-origin runtime written')
