from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / 'api' / 'admin-appointments.js'
text = path.read_text(encoding='utf-8')
pattern = re.compile(r"if\(!\['OWNER','ADMIN','MANAGER','SECRETARY','RECEPTION'\]\.includes\(identity\.role\)\).*?return json\(res,\{patient:updated\[0\],provider:'appwrite-neon'\}\);", re.S)
replacement = """if(!['OWNER','ADMIN','MANAGER','DOCTOR','SECRETARY','RECEPTION'].includes(identity.role))return json(res,{error:'forbidden'},403);let body={};try{body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});}catch{return json(res,{error:'invalid_json'},400);}const patientName=String(body.patient_name||'').trim();const phone=String(body.patient_phone||'').trim();if(!id||!patientName||!phone)return json(res,{error:'patient_name_and_phone_required'},400);if(patientName.split(/\\s+/).filter(Boolean).length<3)return json(res,{error:'patient_name_must_have_three_parts'},400);const before=await identity.sql`select id,mrn,patient_name,patient_phone,patient_phone_normalized,patient_email,date_of_birth,gender,marital_status,residence,height_cm,weight_kg from public.clinic_patients where id=${id}::uuid limit 1`;if(!before[0])return json(res,{error:'patient_not_found'},404);const normalized=phone.replace(/[^\\d+]/g,'').replace(/^00/,'+').replace(/^01(?=\\d{9}$)/,'+20');const dob=body.date_of_birth?String(body.date_of_birth):null;const height=body.height_cm===null||body.height_cm===undefined||body.height_cm===''?null:Number(body.height_cm);const weight=body.weight_kg===null||body.weight_kg===undefined||body.weight_kg===''?null:Number(body.weight_kg);if(height!==null&&(!Number.isFinite(height)||height<30||height>250))return json(res,{error:'invalid_height'},400);if(weight!==null&&(!Number.isFinite(weight)||weight<1||weight>500))return json(res,{error:'invalid_weight'},400);const updated=await identity.sql`update public.clinic_patients set patient_name=${patientName},patient_phone=${phone},patient_phone_normalized=${normalized},patient_email=${body.patient_email?String(body.patient_email):null},date_of_birth=${dob},height_cm=${height},weight_kg=${weight},gender=${body.gender?String(body.gender):null},marital_status=${body.marital_status?String(body.marital_status):null},residence=${body.residence?String(body.residence):null},updated_at=now() where id=${id}::uuid returning id,mrn,patient_name,patient_phone,patient_phone_normalized,patient_email,date_of_birth,gender,marital_status,residence,height_cm,weight_kg,active,created_at,updated_at`;await identity.sql`insert into public.clinic_audit_log(actor_staff_id,action,entity_type,entity_id,before_data,after_data) values(${identity.staff.id},'PATIENT_DEMOGRAPHICS_UPDATED','clinic_patient',${id},${JSON.stringify(before[0])}::jsonb,${JSON.stringify(updated[0])}::jsonb)`;return json(res,{patient:updated[0],provider:'appwrite-neon'});"""
new, count = pattern.subn(lambda _match: replacement, text, count=1)
if count != 1:
    raise SystemExit('FAIL-CLOSED: canonical patient demographics PUT boundary was not found exactly once')
path.write_text(new, encoding='utf-8')
print('[AZAAD patient demographics API] PASS: Appwrite/Neon doctor-authorized demographic update + audit boundary enforced')
